### ISSUE TITLE
Error when setting up Kresus: ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by Abbo44** [bnjbvr/kresus#101]
Hi,

Today, when i tried to go to the kresus app, a pop-up with : 
Error when setting up Kresus: ReferenceError: Symbol is not defined is showed.

**Comment by bnjbvr** [comment]
Hi, thanks for reporting. This can happen if you're using a browser which doesn't implement JS [Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), which is the case for IE, Safari, old Chromium based and old Firefox based browsers. If you're using one of the two last ones, I recommend updating your browser. Anyhow, I'll use a polyfill for older browsers.

**Comment by Abbo44** [comment]
I updated my Firefox Browser and it works ! Thank you !
