### ISSUE TITLE
On mobile version of kresus, the menu is not "on top"

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#103]
Hello,

on version 0.5.1 of kresus, when I use my smartphone to see kresus, when the menu is open, it is not possible click it, as it seems that the "clickable" area is the page itself, not the menu.
Browser : firefox obile for android (last beta version)

**Comment by bnjbvr** [comment]
Thanks for opening this issue, I've noticed it as well. Unfortunately my CSS skills probably won't be helping here...

**Comment by marienfressinaud** [comment]
The menu is "clickable" but it's really painful to find where to click... since I use Kresus mostly on tablet and the behaviour is similar, it would be really cool to have a loot at this (who said that I should take the action? :D)

**Comment by bnjbvr** [comment]
Seems that #291 fixed this, at least for me (Firefox for Android). Even though it's very slow, the menu is now showing up and disappearing when clicking the hamburger menu.
@ZeHiro, can you confirm please?

**Comment by bnjbvr** [comment]
Assuming it's fixed, closing the issue. Feel free to re-open if it isn't the case.

**Comment by ZeHiro** [comment]
@bnjbvr yes, it is fixed.

**Comment by marienfressinaud** [comment]
Thanks guys! :)
