### ISSUE TITLE
aïe problem with kresus

### ISSUE THREAD

**Issue by christi9n** [bnjbvr/kresus#108]
Hi,
I'm under DEBIAN 8 (Jessie ;o)) 64 bits with Iceweasel 38.0.1

I installed Kresus and try to set up an account but I've got the following message
![capture du 2015-05-25 18 50 21](https://cloud.githubusercontent.com/assets/11626946/7800150/157739d0-0311-11e5-8ecd-0679bfcfcc21.png)

Many thanks for your help ;o)

**Comment by bnjbvr** [comment]
Hi, thanks for reporting! Unfortunately, the interesting part of the error message is at the bottom, not at the top of the alert message. Is there any way you could reproduce it again, and transcript the entire message, please?

**Comment by christi9n** [comment]
Sorry ;o)) herewith the whole window
![capture du 2015-05-26 17 13 04](https://cloud.githubusercontent.com/assets/11626946/7815749/9b6211dc-03ca-11e5-99d6-814d8ac9e59a.png)

**Comment by bnjbvr** [comment]
Are you sure your login/password combination is correct? Do you have 2-steps authentication on? (if that's the case, you might need to disable it, for having Kresus to work)

A nice test would be to try to login using weboob/boobank with your credentials and check whether this works or not.

**Comment by christi9n** [comment]
au temps pour moi ... I tried with another bank account and it's OK. The first bank account password was KO ! Many thanks and Bravo ;o))

**Comment by bnjbvr** [comment]
Merci !
