### ISSUE TITLE
Operations order is not deterministic

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#109]
STR:
- load operations list
- click "sync now"

Expected:
Order of operations is the same between the first and the second time.

Observed:
It isn't.

**Comment by nicofrand** [comment]
Is that why sometimes the operations are unordered ?

![kresus-bug](https://cloud.githubusercontent.com/assets/3419050/8979496/6b3d3d34-36aa-11e5-9f68-e0921c9363ef.png)

**Comment by bnjbvr** [comment]
No it's a different bug. I need support for debugging this: in the next version, there'll be an "export" feature, so that you can export an entire kresus instance (without the bank password). Would you be ok with sending me a sample of your operations with the unordered ones, when this feature gets released, please?

**Comment by nicofrand** [comment]
Yes I would :). This app is really awesome (my bank ING has something like this with categories and so on but the charts are really lame comparing to Kresus) !

Do you want me to file a new bug for this then ?

**Comment by bnjbvr** [comment]
Thank you! Yes, feel free to open a new bug to keep track of this :)
