### ISSUE TITLE
Search fields not reseted

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#113]
When search fields over operations are active, they are not resetted when changing of account, is it a desired function?

**Comment by bnjbvr** [comment]
Well, that's a good question. Should there be a default behavior (for instance, clear the search field when changing banks) or should the user be able to choose how this behaves?
In my sense, the default behavior should be to let the fields as they are, and the user would click on "clear form" to reset the form. That currently has the bad side effect of closing the search form, maybe I should fix this instead?

**Comment by bnjbvr** [comment]
Now that we have a "clear" button which doesn't close the search panel, it sounds fine to me that the current behavior stay the same. What do you think @ZeHiro ?

**Comment by ZeHiro** [comment]
@bnjbvr seems googd to me. I close. ( @nicofrand thanks for closing this one :))
