### ISSUE TITLE
Move 'Reinstall weboob' button

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#114]
In the parameters view (advances), the 'reinstall weboob' button is right at the place you would expect a validation button for the parameters to be. You could launch the reinstall of weboob thinking you validate the new parameters.
By the way a real 'Validate parameters' button could be used (without this you never know when they are valid)

**Comment by bnjbvr** [comment]
Right, makes sense. A "validate parameters" wouldn't have any effects, as parameters are saved as soon as they're changed. I'll move the button to the leftmost side of the screen to prevent the issue. Thanks for reporting!

**Comment by ZeHiro** [comment]
Thanks for fix, but I still automatically clicke on this %@?! button (and the reinstall is loooong on a RPI2). A validation popup could be possible?

**Comment by bnjbvr** [comment]
Hah. I'll consider this. Another solution would be to hide this under "very advanced preferences", or move it to another settings section, as the "advanced" tab is getting heavy (now that it has the import/export features). Any preference?

**Comment by ZeHiro** [comment]
Or "Danger Zone" in red (like github repo)

**Comment by bnjbvr** [comment]
The "Reinstall" button is now in a "Weboob" subsection of the settings, so if you mistakenly press the button there, that is because you wanted to touch Weboob anyway. I'm considering this is fixed.
