### ISSUE TITLE
Can't open the application (check that first install works fine)

### ISSUE THREAD

**Issue by babolivier** [bnjbvr/kresus#116]
When I launch the app, I get a blank screen for a few seconds, then an alert pups up with this content (sorry html mess this up):

<code><pre>Error when setting up Kresus: xhr error: Gateway Time-out
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>Error 504 Gateway Time-out</title>
<style>

</style>
</head>
<body>
<blockquote>
	<h2>Error 504 Gateway Time-out</h2>
	<p> This cozy is not responding.
	<ul>
		  <li><b> The proxy may be crashed</b> - Please contact us at <a href="mailto:contact@cozycloud.cc">contact@cozycloud.cc</a>. Provide us this url, so we can fix it. </li>
	</ul>
</blockquote>
</body>
</html></pre></code>

**Comment by bnjbvr** [comment]
Thanks for reporting. It looks like your entire cozy is down. If not, you can try to uninstall and reinstall Kresus, maybe? Not sure what would cause an infra issue like that.

**Comment by babolivier** [comment]
Yup, tried it, no change. And I don't see how the Cozy is entirely down, since I can use other apps, change the Cozy's settings, etc. Also tried to reboot it, no change.

**Comment by nicodel** [comment]
Hi I have a similar issue when I try to launch kresus. It is the first time I launch kresus since cozy was updated to 2.0.
Cozy instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.0
Proxy: 2.0.0
Home: 2.0.1
Controller: 2.0.24
Kresus:  0.5.1
![capture du 2015-06-18 14-57-57](https://cloud.githubusercontent.com/assets/1799460/8231805/53ee1824-15cb-11e5-8e8f-8a963781e8cf.png)

**Comment by nicodel** [comment]
OK. I restarted Cozy, got notifications for updates of Data Systme and Home.
Data System: 2.0.3
Home: 2.0.2

Kresus is launched and works fine now.

**Comment by babolivier** [comment]
Same, I updated my Cozy, and Kresus works fine now.

**Comment by bnjbvr** [comment]
Strange. I'll check that kresus is installing fine the first time on a new empty cozy.

**Comment by bnjbvr** [comment]
Just retried on an hosted CC instance, worked fine... the second time. It seems there is some race condition in the installation process that went in the way of Kresus. Opened https://github.com/cozy/cozy-controller/issues/67
If that ever happens again, I recommend reinstalling / restarting Kresus :/
