### ISSUE TITLE
Add birthday date to register form (needed for ING)

### ISSUE THREAD

**Issue by victornoel** [bnjbvr/kresus#119]
Hi,

I just tested a bit this app and it seems that ING Direct is not working… It complained with the following message when I tried to add the account:
```
xhr error: Internal Server Error
Error when parsing weboob json: Backend(ing): Configuration error: Missing parameter "birthday" (Date de naissance)
```

It is true that when authenticating on the ing direct website, the birthday is needed…

**Comment by bnjbvr** [comment]
Thanks for reporting. I'll add an option for that, if weboob supports it.

**Comment by victornoel** [comment]
Great, it should be the case: it is one of the declared parameter of the module according to the source code... So it is not an option, it is always needed for the ING module to work :)

**Comment by YoranSys** [comment]
Hi, 
victornoel you can use ING direct with kresus, for that you have to modify 
weboob/py/endpoint.py and add parameter birthday.

>        params_connector = {
>            'login': self.login,
>            'password': self.password,
>            'birthday': DDMMYYYY,
>       }

This very bad but it work. 

Note: if you have other account without birthday this does not seem a problem.

**Comment by bnjbvr** [comment]
Thanks @YoranSys for the format of the birthday field, I wasn't too sure what it would be.

**Comment by ooii** [comment]
Thanks for the hint @YoranSys but by adding this field, it doesn't work for other banks which do not require it (eg. Hello Bank).

**Comment by ooii** [comment]
I fixed (temporarily) this issue by editing the following:
```
params_connector = {
            'login': self.login,
            'password': self.password,

        }

        if self.website is not None:
            params_connector['website'] = self.website

        if self.login == '#####':
            params_connector['birthday'] = DDMMYYYY
```
Where `#####` is my ING account number.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/01fddc0766803c9b0bbef6fec47728aa4e70acea
