### ISSUE TITLE
Problem with postinstall.sh

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#125]
After a new install trial failing due too long npm install request, I finished the install by hand : 

sudo npm install

then 
sudo ./node_modules/gulp/bin/gulp.js b && ./postinstall.sh
Here is what I got  (gulp was run without error) : 

chown: changing ownership of `./weboob/requirements.txt': Operation not permitted
chown: changing ownership of `./weboob/scripts/accounts.sh': Operation not permitted
chown: changing ownership of `./weboob/scripts/operations.sh': Operation not permitted
chown: changing ownership of `./weboob/scripts/install.sh': Operation not permitted
chown: changing ownership of `./weboob/scripts/test.sh': Operation not permitted
chown: changing ownership of `./weboob/scripts': Operation not permitted
chown: changing ownership of `./weboob/banks-all.json': Operation not permitted
chown: changing ownership of `./weboob/py/accounts.py': Operation not permitted
chown: changing ownership of `./weboob/py/operations.py': Operation not permitted
chown: changing ownership of `./weboob/py/lib.py': Operation not permitted
chown: changing ownership of `./weboob/py/connector.py': Operation not permitted
chown: changing ownership of `./weboob/py': Operation not permitted
chown: changing ownership of `./weboob/.gitignore': Operation not permitted
chown: changing ownership of `./weboob': Operation not permitted

I didn't use cozy-kresus user (sudo -u cozy-kresus) to run this last command as I got write errors on compiling the js client with gulp command. 

I think a sudo is missing before launching the scripts  (they are run by the controller which has root rights)

command should be in the package.json : 

sudo ./node_modules/gulp/bin/gulp.js b && sudo ./postinstall.sh

The distro used in raspbian wheezy (cozy image for RPI2)

**Comment by bnjbvr** [comment]
So, the postinstall script tests whether there is a `cozy-kresus` user before chmoding the directory. The intent hidden behind this is that the postinstall is run by the root user, and thus has the rights to apply the chmod.

Can it be that `sudo ./node_modules/gulp/bin/gulp.js b && ./postinstall.sh` is actually equivalent to ` (sudo ./node_modules/gulp/bin/gulp.js b) && ./postinstall.sh` in your shell?

**Comment by bnjbvr** [comment]
I forgot to add: can you try with `sudo ./postinstall`, please?

**Comment by ZeHiro** [comment]
I did, it worked fine. (I updated the first comment) to suggest a double 'sudo' use

**Comment by bnjbvr** [comment]
Cool, I think we're all set here. Can we close? If you feel like it, feel free to add a comment in the readme or the postinstall script stating that this one should be run with the root rights?

**Comment by ZeHiro** [comment]
shouldn't be the package.json updated ?
If you consider not, then close

**Comment by bnjbvr** [comment]
Good call! Rather than running the postinstall.sh script with `sudo` (we're not even sure `sudo` is installed on the machine, and I'd rather not add requirements...), I've added an explicit error message proposing a few possible solutions to the problem.

**Comment by ZeHiro** [comment]
Perfect!.
