### ISSUE TITLE
Add packages dependencies in the readme

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#134]
- `python-dev`
- `libffi-dev`

Find out what the others are...

**Comment by bnjbvr** [comment]
- `libyaml-dev`
- more than 1 Gb of RAM for the compilation (?)

**Comment by AwYiss** [comment]
In order to have `npm install` complete successfully, I had to install the following packages (on Fedora 22) :

* `python-devel`
* `libffi-devel`
* `libxml2-devel`
* `libxslt-devel`

**Comment by ZeHiro** [comment]
!GB is enough to compile. The compilation takes it time, but finally finishes without problem on RPI2.
I would add 
´´´
libyaml-dev  (el) 
´´´

**Comment by ZeHiro** [comment]
Couldn; t these sependencies installes by the install.sh script? I don'know it there exist a "generic" command exist independantly of the package system used on the distro

**Comment by bnjbvr** [comment]
I don't think so, for exactly the reason you mentioned: there's no such generic command + the packages names would depend from one machine to the other. We've talked about adding ubuntu package names to the list of dependencies of the cozy app (so that would be detected by the cozy platform and run then), but it has the same issue (what if the cozy instance isn't hosted on an ubuntu?).

**Comment by frankrousseau** [comment]
On Debian it is:

* python-dev
* libffi-dev
* libxml2-dev
* libxslt-dev

**Comment by bnjbvr** [comment]
Forgot to add `libyaml-dev` in the readme and makefile.

**Comment by bnjbvr** [comment]
Apparently `libyaml-dev` isn't mandatory.
