### ISSUE TITLE
Since last update, Kresus doesn't work

### ISSUE THREAD

**Issue by silvyn** [bnjbvr/kresus#137]
Hi,
Since the last week update, my Kresus App is broken :'(

I'm hosted on a CozyCloud.cc instance. So I tried to remove app ans reinstall (works for other app). But It doesn't help. I'm still receive notification with new import transaction, but can't open app (I'have the install page with youtube video for waiting).
This morning I've this error message : 

`Error when setting up Kresus: xhr error: Bad Gateway
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>`

If you have any idea, thank you (and for this great app !).
Sylvain

**Comment by bnjbvr** [comment]
Thank you for the report! Can you pastebin the content of the logs, somewhere, please? (it doesn't contain any personal information, no worries about making it public) Feel free to send it by private message to me on the forum, or email to kresus at benj dot me. Cheers!

**Comment by silvyn** [comment]
Hello, email send :)

The last few lines : 

>[install.sh] --   Running setup.py install for cryptography
>[install.sh] --     c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
>[install.sh] --     compilation terminated.
>[install.sh] --     Traceback (most recent call last):
>[install.sh] --       File "<string>", line 1, in <module>
>[install.sh] --       File "/usr/local/cozy/apps/kresus/weboob/env/build/cryptography/setup.py", line 342, in <module>

**Comment by bnjbvr** [comment]
Ha, probably libffi-dev missing... See also https://github.com/bnjbvr/kresus/issues/134

**Comment by silvyn** [comment]
So I have to open issue to Cozy team ?

**Comment by bnjbvr** [comment]
Yes; the email I've sent to nledez should be enough. Let's wait and see.

**Comment by bnjbvr** [comment]
Fixed thanks to nledez' help.
