### ISSUE TITLE
Change "close" button's color in transactions search to orange

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#142]

**Comment by robinmoussu** [comment]
As said in cosy forum, I can do it. Is there somewhere a theme's color list, or do I pick a random nice orange?

**Comment by bnjbvr** [comment]
The line to change is there: https://github.com/bnjbvr/kresus/blob/incoming/client/components/SearchOperationList.js#L201

The class `btn-primary` gives the blue color, as described on http://getbootstrap.com/css/#buttons . Changing it into `btn-warning` would make it the same orange as on the website, which looks good, IMO. If you're willing to choose another color (another orange), you'll have to add a CSS class and implement it in the stylesheet.

If you're still willing to implement this, please follow the dev rules as indicated in https://github.com/bnjbvr/kresus#can-i-propose-a-pull-request . Good luck!

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/378b3244ff5fb8e0355a0b0f5b84de1add82c6bb
