### ISSUE TITLE
Passwords get lost

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#148]
Hello @bnjbvr,
I got this error in my logs: 
```
Error when polling accounts: when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: Backend(bp): Configuration error for field "password": Value "undefined" does not match regexp "^(\d{6}|)$"
```
And the import of operations didn't work.
It seems that the password for the bp module (banque postale) is not defined, but it appears in the databrowser.

Any idea?

**Comment by bnjbvr** [comment]
Thanks for the report. I have no idea what's going on with these lost passwords. It's troublesome, because it tends to happen more and more often... I'll doublecheck the password path, to see if there can be some race condition somewhere.

**Comment by ZeHiro** [comment]
Re,

It seems to be another thing than just the password loss. After the reboot, I get this on manual imports (same bank): 

```
Error -  when fetching operations for access: when retrieving operations: Weboob error: Traceback (most recent call last):
  File "py/endpoint.py", line 111, in <module>
    content = BankHistoryHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 84, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: 

```

**Comment by bnjbvr** [comment]
What if you try by hand?

```
cd weboob
source ./env/bin/activate
python ./py/endpoint.py bank_id login password
```

**Comment by ZeHiro** [comment]
I tried. The script always freezes here : 

https://github.com/bnjbvr/kresus/blob/master/weboob/py/endpoint.py#L90

The loop is never entered, I tested with a print without condition.

**Comment by ZeHiro** [comment]
My bad, the module is not up to date. It seems the weboob-config does not work in a virtual env.

**Comment by bnjbvr** [comment]
Can you try this to update weboob and weboob modules:

```
cd weboob
source ./env/bin/activate
pip install -U -r requirements.txt
```

**Comment by ZeHiro** [comment]
I did a full reinstall ...
Now I have all the passwords of by bankaccounts deleted in the databrowser....

**Comment by ZeHiro** [comment]
Well I lost ALL my passwords in cozy

**Comment by bnjbvr** [comment]
Sounds like quite a general issue with the cozy data-system. Have you opened a bug on the DS repo?
If it's identified as a general cozy issue, can we close this one?

**Comment by ZeHiro** [comment]
I did open on the DS repo ;)
Let's close this one
