### ISSUE TITLE
Notifications / Emails are not localized

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#154]
The notifications displayed in cozy are not localized (in french at least) whereas the rest of kresus interface is.

![kresus-bug-l10n](https://cloud.githubusercontent.com/assets/3419050/9033222/85fe6a6c-39c5-11e5-8663-4ce85a83cc66.png)

**Comment by bnjbvr** [comment]
Thanks for the report!

**Comment by ZeHiro** [comment]
This issue shold also translate emailed reports

**Comment by bnjbvr** [comment]
Ha, I was pretty sure there was an issue open about that. Fixed by https://github.com/bnjbvr/kresus/commit/8c11d61c257e41e7b31d9e27da2d66b961124c25 .
