### ISSUE TITLE
Weboob error: InsecurePlatformWarning

### ISSUE THREAD

**Issue by clochix** [bnjbvr/kresus#158]
Hi,

Here's an error reported by one of our users. He get the following logs:

```
xhr error: Internal Server Error
Weboob error when importing operations:
when retrieving operations: Weboob error: /usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "py/operations.py", line 21, in <module>
    transactions = BankHistoryHandler(id, password, website).post(bankuuid)
  File "/usr/local/cozy/apps/kresus/weboob/py/lib.py", line 91, in post
    return self.load_from_connector(name, 'get_history')
  File "/usr/local/cozy/apps/kresus/weboob/py/lib.py", line 53, in load_from_connector
    raise Exception("Wrong credentials")
Exception: Wrong credentials
```

**Comment by bnjbvr** [comment]
Thanks for the report. The error message isn't explicit: the last line indicates what's wrong. In this case, the password is incorrect. Two choices:

1) it's been erased by the data system, as it sometimes happens with konnectors.
2) the user's provided password has been changed or blocked by the bank.

Can you provide me with the user's nickname on irc, or something else so that I can reach them out, please?

**Comment by ZeHiro** [comment]
Hey,
it looks like https://github.com/bnjbvr/kresus/issues/148 and the DS problem identified here :  https://github.com/cozy/cozy-data-system/issues/153

**Comment by clochix** [comment]
The affected user has checked, and in fact its password had expired. After updating it, everything works fine now. Maybe should you ask users to check their credentials when sync fails ? Anyway, I think we can close this one, thanks !

**Comment by bnjbvr** [comment]
The dev branch `incoming` has better error messaging for this kind of cases. Thanks for letting me know!
