### ISSUE TITLE
Add operation types in the research of operations

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#178]

**Comment by bnjbvr** [comment]
And in the duplicates search algorithm as well.

**Comment by ZeHiro** [comment]
Usually, duplicates appear when:  
-  an operation is "pending"/"being processed" on the website. The operation type is the "type.unknown"
- the operation is imported clearly (with the operation is "completed"). The operation type is then clearly defined. 

In this case the kept "operation type" should be the "not unknown" one. 
I don't know if operation type can be used to detect "duplicates".

**Comment by bnjbvr** [comment]
So, could we use the duplicate operation type to **not** import operations that have a type which is "type.unknown"? That could probably prevent a few duplicates, but that works only if *all* operations get a type at the end.

**Comment by ZeHiro** [comment]
No, because the operation type is allocated by weboob using regexps over the 'libellé'. And some operations, even if they are completed still have an unkown type

**Comment by bnjbvr** [comment]
Good to know, thank you.

**Comment by bnjbvr** [comment]
I'll take care of this too.

**Comment by ZeHiro** [comment]
To test: does the research results update on operation type change?

**Comment by bnjbvr** [comment]
How do you mean? The operations list updates whenever a field is changed in the search form, of course, so I guess I misunderstood your question :)

**Comment by ZeHiro** [comment]
Use case (but cannot be tested as the modification of operation type of an operation is only on my repo): 
- Filter operations over operation types (let say "Unknown") 
- Change operation type of a given operation to a defined one (let say "Card")
- This operation should disappear of the result list

**Comment by bnjbvr** [comment]
That's more generic to search and independent. Actually I really don't think instant feedback is needed for this use case, but I could be convinced (with a pull request :)).

**Comment by ZeHiro** [comment]
Of course, it is not a bug, but I wanted to track this :) 
Using the research over operation types looks a way to make a "batch update" of operations without types. But it may not be necessary to have this update implemented, At least I wanted to be sure it wouldn't raise any problem.

**Comment by ZeHiro** [comment]
Maybe filters over categories and types could be on the same line

**Comment by bnjbvr** [comment]
Feel free to open a PR ;) Also, the detailed view of a single operation is now a bit ugly and would appreciate some update :)
