### ISSUE TITLE
In research view, clicking "Empty/Vider" shouldn't hide the research pane

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#182]

**Comment by nicofrand** [comment]
Is everyone ok to make the "clear" button only clear the search form content and not close it ?
If it is ok, I could work on it.

That makes me think that we should find an intuitive way to tell "Click on 'Search' to display/hide the search form' : currently I do not think it is clear enough.

**Comment by bnjbvr** [comment]
Here is another proposal:

- when the panel is open: have a "close" warning button on the left, keep the "empty" button on the right. The close button would empty *and* close, the empty button would just reset the form.
- when the panel is closed, have a + button at the right (as for the "Configure a new account" panel in the settings section).Clicking the + button would open (and close) the panel.

What do you think?

**Comment by ZeHiro** [comment]
I like it

**Comment by nicofrand** [comment]
I initially thought of a "clear and close" button but that would not solve the "open" case.

Maybe we should create another ticket for the "+" button that would toggle the form ? When open, the button would then become a "-".

**Comment by nicofrand** [comment]
I also think the "Close" button should say "Clear and close" instead of just "Close" : let's imagine we are on a mobile, we want to keep the form but just want to gain some place by hiding the form. "Close" would be confusing I think.

**Comment by bnjbvr** [comment]
I agree that "close" wouldn't be enough information, but "clear and close" is definitely too long. Maybe "leave", or "leave search"? I don't quite know...
Regarding the +/- button toggling the form, it can be either done in the same PR, different commit or in the same commit, or in different PRs different commits, I don't mind any way :)

**Comment by nicofrand** [comment]
OK, to summarise:

* For the +/- buttons I opened an [issue](https://github.com/bnjbvr/kresus/issues/259)
* A "Clear & close" button is added on the left, with the "btn-warning" class (like the "clear" button)
* The "Clear" button on the right only reset the form, without hiding it

I'll work on both.
