### ISSUE TITLE
Duplicates detection not deterministic between browsers

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#188]
Using Firefox (41b)(private mode) the duplicates are correctly detected.
However, using Chrome 44 (private mode), several of them are missing (whereas they should : same label/date/amount when I check the reports).

Firefox console log:
```
Similarity Component - Running findRedundantPairs algorithm... main.js:38:14
Similarity Component - Input: 1216 operations main.js:38:14
Similarity Component - Threshold: 86400000 main.js:38:14
Similarity Component - 33 pairs of similar operations found
```

Chrome console log:
```
Similarity Component - Running findRedundantPairs algorithm...
main.js:38 Similarity Component - Input: 1216 operations
main.js:38 Similarity Component - Threshold: 86400000
main.js:38 Similarity Component - 3 pairs of similar operations found
```

**Comment by bnjbvr** [comment]
Thanks for the report. Quite a simple fix, but that makes me think the algorithm wouldn't find all duplicates before my patch :/
