### ISSUE TITLE
Charts default period settings does not work

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#189]
Steps:

0. Go to "Settings"
0. Click on "Default parameters"
0. Select "6 last months" (or anything else but "All times") in the "Chart: default period" dropdown
0. Click on any other settings tab, for example "Bank accounts"
0. Click on "Default parameters" again

What I expect:
* The "Chart: default period" dropdown value is "6 last months"
* When I navigate to "Graphics", every chart (category + balance) is displayed for the 6 last months only

What happens:
* The "Chart: default period" dropdown value is still "All times"
* When I navigate to "Graphics" the dropdown value is "6 last months" BUT:
 * For the "by category" chart there are the last 6 months + the current month (ie. march to september as today)
 * For the account balance and the differences charts, I have values since the beginning (2012)

**Comment by bnjbvr** [comment]
Thanks! However, the balance chart doesn't have a dropdown, so you can't select a period there, that's a different issue (and a feature request more than a bug). You're right that the setting is wrongly displayed though, but fortunately the fix is easy...

**Comment by nicofrand** [comment]
Ok ! Not a problem for the balance, I just wanted to be clear enough :).

**Comment by bnjbvr** [comment]
Fixed as https://github.com/bnjbvr/kresus/commit/8aee977d4c58afbd91753494a2553758bc4d1c3f for the wrong value in the default setting dropdown.

**Comment by bnjbvr** [comment]
As for the other issue (last 3 months charts include the current month + last 3 months), I think it's actually useful to keep as is. Whether the current month should be included or not is unclear to me. The only strange part is that one asks for the last 3 months chart and sees 4 months, but other than that, it looks pretty reasonable.

**Comment by nicofrand** [comment]
I agree: the current month might be useful, I only included it in my
description to be sure that was intended.

Le mar. 8 sept. 2015 23:38, Benjamin Bouvier <notifications@github.com> a
écrit :

**Comment by bnjbvr** [comment]
Yeah, sorry if my tone was a bit rough, it was quite late and I was merely thinking out loud :) This is something weird for sure, maybe having a toggle "include current month" would make it clearer...
