### ISSUE TITLE
Infinite scrolling: In the operations table, only print entries that can be shown inside the screen

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#2]
See also http://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome

**Comment by bnjbvr** [comment]
http://robert.ocallahan.org/2014/02/implementing-virtual-widgets-on-web.html
http://people.mozilla.org/~roc/virtual-list-demo.html

**Comment by bnjbvr** [comment]
Approximately resolved: show only a subset of operations in the front page, and set a timer to show X more operations every Y milliseconds. Works for me (thanks for the trick @padenot).

**Comment by jankeromnes** [comment]
Nice one!
