### ISSUE TITLE
Make order of duplicates deterministic

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#212]
The order of duplicates is not deterministic. The duplicates should be ordered by : 
- Latest import date (largest import date of both  operations)
- First import date (smalled import date of both operations), in case there are 3 duplicates or more

Maybe not necessary to fix in current duplicates due to #132

**Comment by bnjbvr** [comment]
Strange: operations are sorted, and the computation of duplicates is directly based upon the operations array. I could buy that duplicates happening at the same span are sorted in a random way (because that's probably browser specific)(and I suspect Firefox's ensuring that the sort is stable, because it's so nice). Is this what you observe?

**Comment by ZeHiro** [comment]
I observe random order of duplicates, but I can't tell what is the cause. 
Current exemple on my kresus: 
- First duplicate : Operation date is 4/09/15 
- Second duplicate : Operation date is 14/07/15
- Third duplicate : Operation date is 4/09/15

About duplicate detection, how about unsetting duplicates if they are imported on the same date (or with import date difference smaller than x mins)? All the real duplicates I can see with my main bank (LCL) on my kresus are: 
- First operation : operation ongoning but not yet final, usually declared with label "operation carte" or so
- Second operation : final operation declared with the real label.

They are all the time imported on different dates (usually with 1 day difference). The false duplicates I have (see #123) are two different operations (but same date/amount and same labels) and they were imported on the same date/hour. This won't reject all false positive, but would at least reject these. 
Why this would work? Because if they were imported on the same date/hour, this means they were served at the same time by weboob, which means, except if there is a bug in weboob or kresus import process, that the two operations are distinct.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/74cd37ddaeceb78a16fd1607633caab4b9f07a40 .
