### ISSUE TITLE
Opertion type selection of first element in the list is impossible when no operation type is set

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#214]
Let an operation without operation (imported before operation types were imported from weboob).
The operation has "None" operation type.
If the user wants to select the first operation type in the list (usually Carte/Card), the operation type won't be updated, as there is no change in the select element (the "None" operation type is not in the list).
To allocate the operation type in this cas, the uses must first select a type different from the first one in the list, and then reselect in the list.

Correction : 
The onBlur event should also update the operation type.

**Comment by bnjbvr** [comment]
Can reproduce. Thanks for opening the issue.
