### ISSUE TITLE
Operation types labels not displayed

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#216]
Some operation types labels appear to be missing in the dropdown:

![bug-kresus](https://cloud.githubusercontent.com/assets/3419050/10013537/7bb72eb2-6112-11e5-9a0d-c5fb6addd760.png)

When using Cozy in french, some localization errors are displayed in the client console:

```
Missing translation key for "t.unknown" main.js:90:9
Missing translation key for "t.order" main.js:90:9
Missing translation key for "t.transfer" main.js:90:9
Missing translation key for "t.check" main.js:90:9
Missing translation key for "t.deposit"
```
However, using Cozy in english did not fix the issue since there are still some blank options in the dropdown (there are no localization errors though).

I erased my browser cache but that did not help.
Same problem on Firefox desktop (40.0.3) and Chrome (all the blank fields appear on top in Chrome though).

**Comment by ZeHiro** [comment]
Hi @nicofrand ,

could you give a look to the databrowser for doc types "operationtype" and checke that all the "name" field are like : 

"type.toto" and not "t.toto".

And stop an start kresus if this fixes the problem.
Thanks.

**Comment by nicofrand** [comment]
No, they are not correctly named:

```
t.unknown	0	
t.order	2	
t.transfer	1	
type.card	7	
type.withdrawal	6	
t.check	3	
type.payback	5	
t.deposit	4	
type.bankfee	9	
type.cash_deposit
```

Is there any way I can renamed them as wanted (there is not "edit" icon in the databrowser) ?

**Comment by ZeHiro** [comment]
Cool. I knew i shouldn't have updated the names of operation types. This takes time to update them. @bnjbvr is this the race condition you feared?

**Comment by bnjbvr** [comment]
Yes, that's probably it. The right way to fix this on the server is to break all races in a sequential fashion, at startup. I'll take care of it for the next version.
