### ISSUE TITLE
Add a custom label to an operation

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#217]
Maybe I am mistaken and this is not Kresus' job but I would find great to be able to assign a custom label to an operation.

Since all I see is a number, (even if it is a check number, most of the time I do not remember why I wrote a check. 

If I could say somewhere that this transaction is for example "Library X for book YYY" that would help me 3 months later to know that the check was for the library "X" and for the purpose of a nice book named "YYY".

**Comment by bnjbvr** [comment]
Cool, that's something I've wanted too, and other people have been asking me about it as well. Definitely on the close roadmap, it shouldn't be too hard to implement! If you're willing to do it, that's a field to add in `models/operation.js` and a few things to change in the client ;)

**Comment by ZeHiro** [comment]
Hi @nicofrand ,

I've implemented a first version for custom labels.
if you want to try, it's in this repo : 
https://github.com/ZeHiro/kresus/tree/incoming-custom-label

Currently the custom label is only visible in the detailed operation view.
Here is an exemple with an operation without custom label, one with a custom label.
![selection_534](https://cloud.githubusercontent.com/assets/7999082/10071752/7b52e424-62bc-11e5-8b39-0413d3a2916d.png)
What do you think? Any comment on the order of information/typo/colors...? 
The selection button works the same as for types/categories except it is faded and italic.

**Comment by nicofrand** [comment]
I can't test right now (I am on holidays) but that seems great except
"personnalisé" with 2 n :).

**Comment by bnjbvr** [comment]
Looks nice! Although having the custom label in under the detailed operation view makes it much less useful, in my opinion. How about:

- having the custom label replace the simple label all the time, if it's set (otherwise, keep on printing the simple label).
- in the detailed view, show both the raw label and the simple/custom label.

That makes it much more useful, and people would clearly understand they can modify it by hovering onto it in the transaction lists.

**Comment by ZeHiro** [comment]
![selection_536](https://cloud.githubusercontent.com/assets/7999082/10101138/f3d2855a-6396-11e5-8de3-55c12d400cdb.png)

And here is how it is now. There still is a small problem to fix (the MAX LENGTH of labels is not used for custom labels). But it is now possible to set a custom label from the main operation list. 

But one of my main concern, is that the text is not wrapped on button labels, and as there are now button on 3 columns, there might be some lisibility problems on narrow screens

**Comment by nicofrand** [comment]
I cannot test anymore (my instance is broken), I will if I manage to fix it.
