### ISSUE TITLE
Synchronization date is wrong

### ISSUE THREAD

**Issue by EtienneM** [bnjbvr/kresus#220]
Hi!

I have Cozy installed on a Raspberry PI at home. Since the last Kresus update, the "Last synchronization with your bank" field is wrong. I manually updated it and the date that appears is 1 day too early. I think it appeared with the last update.

**Comment by bnjbvr** [comment]
Thanks for the report! It does look strange, especially because nothing has really changed on that matter. Are you using the `master` or the `incoming` branch? Can you make sure your Rpi time settings are correct? What timezone are you in?

**Comment by bnjbvr** [comment]
Hey @EtienneM, any news here?

**Comment by EtienneM** [comment]
Sorry I was overwhelmed with work. 

And I am truly sorry because it was just a problem with my NTP configuration on the server... Shame one me :sweat:

**Comment by bnjbvr** [comment]
No problem, thanks for keeping me up to date!
