### ISSUE TITLE
Too few details in a transfer label

### ISSUE THREAD

**Issue by EtienneM** [bnjbvr/kresus#221]
Hi 

My bank is "Crédit Coopératif" and when I have a transfer, the label is not comprehensive. On my bank website I can see that the information you display matches only the "Détails de l'opération" field. However, if I transfer money to a friends bank account using the text field, it appears in the field "Libellé de client à client". There is also some interesting information in the field "Référence de client à client".

**Comment by bnjbvr** [comment]
Any chance you could try with Weboob and see whether it yields more information than Kresus does? K just retrieves the labels based on what Weboob returns, so I am not entirely sure there's much more to do here.

**Comment by bnjbvr** [comment]
Any news here, @EtienneM ?

**Comment by EtienneM** [comment]
OK can you point a tuto on how to try with Weboob ?

I will try to debug it quickly now that I have some times

**Comment by bnjbvr** [comment]
Well, I am not aware of any tutorial, but I am pretty sure your favorite search engine is :)

e.g. ddg leads me to https://doc.ubuntu-fr.org/weboob

**Comment by EtienneM** [comment]
Indeed you get all the information provided by the weboob command `history`. I opened a bug report in the [Weboob repository](https://symlink.me/issues/2176).

**Comment by bnjbvr** [comment]
Thank you, I think we can close this issue, as it's not something we can fix in Kresus (unless you're willing to write your own scrapper for Credit Cooperatif in JavaScript :)). Cheers!
