### ISSUE TITLE
Importing operation types shouldn't duplicate them

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#223]
Hi,
here is what i observed on my test instance.
- I have several accounts with existing operation types
- I imported a kresus instance from an export of my day to day instance (using operation types also)

Acter import, the operation types are duplicate in the DB: one from the original DB, one from the import.

This can cause multiple problems if the imported operation types are not imported : 
- the imported operations are imported with the ID of their operation type. If the operation type is not retrieved from its ID by the client, an error is raised. 

the same problem could occur with categories. 

Possible solution: 
- export operation type with weboob value instead of operation type ID. And on import, check if a type exists with the given weboob value. If it does, set operation type to the ID of this type. If not, delete operation type of the model for the given operatoin (the client will show operation type: none)

**Comment by bnjbvr** [comment]
Yep. See also #174, which is the same problem but for categories (and there we could check for labels).
More generally, maybe import should be incremental and we should check for operations that haven't been imported into the database, etc.
