### ISSUE TITLE
Merging operations does not merge operation types

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#226]

**Comment by bnjbvr** [comment]
Well, it's supposed to, at least: https://github.com/bnjbvr/kresus/blob/master/server/models/operation.coffee#L3-L7

However, I just realized that there is no such thing as a null operationTypeID, as in the worst case, it's set to `unknown`. That might be a specific case to handle in the operations' controller merge function...

**Comment by ZeHiro** [comment]
The case I obeserved was a null operationTypeID as the result of the merge of two operations which should have an operation type now (there should not be a null operationtypeID anymore).  At least one has an "unknokn" operation type
