### ISSUE TITLE
Missing dependency PyExecJS

### ISSUE THREAD

**Issue by Zauberstuhl** [bnjbvr/kresus#234]
> Unknown error, please report: Please install PyExecJS

Happened after I tried adding my PayPal account

**Comment by bnjbvr** [comment]
Thanks for the report! I will add this for the next version.
In the meanwhile, you can fix it by doing the following:

```
cd weboob
. ./env/bin/activate
pip install pyexecjs
```

**Comment by Zauberstuhl** [comment]
cheers

**Comment by Zauberstuhl** [comment]
I also had trouble when I tried installing kresus via cozy-dev (vm vagrant)

following libs were missing:
+ libjpeg-dev
+ libffi-dev

@bnjbvr

**Comment by bnjbvr** [comment]
Right, these are specified in the readme, and you can install them with `make install-debian-deps`, as indicated there.

**Comment by Zauberstuhl** [comment]
ah ok I thought I missed something cheers

**Comment by bnjbvr** [comment]
Cool, thank you for reporting!
Also, I see you're doing some nice stuff on your fork. Note that if you're willing to send the changes upstream, you'll need to base your work on the `incoming` branch. Pull requests gladly accepted and thanked with beers ;)
