### ISSUE TITLE
Charts only havde 10 colors

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#237]
When you have 11+ categories, it is disturbing to have several categories with the same color

**Comment by nicofrand** [comment]
All the colors (or only the one above 10 if we want to ensure to have nice colors like here) might be generated like in this [POOC](http://jsbin.com/fudecowuma/edit?html,css,js,output).
This does not prevent to have 2 colors that look alike though (and the script should check if the color has already been generated).

**Comment by ZeHiro** [comment]
Other solution would be to have sub-categories. Only the "main/first level" categories would have a different collor. Each subcategory would share the color of a subcategory. (see 'first solution' #39)

**Comment by nicofrand** [comment]
Working on it.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/4b215964340510432b649582e7445c80f6a72086 .
