### ISSUE TITLE
mauvais montant mail

### ISSUE THREAD

**Issue by miton18** [bnjbvr/kresus#244]
Bonjour, krésus m'envoi chaque un mail, avce le résumé des opérations,
mais pour chaque ligne avec le numero de compte le montant entre parenthèse reste a 0
compte C/C *********(0€)

**Comment by bnjbvr** [comment]
Salut, merci pour le rapport. Quelle version de Kresus utilises-tu ? L'envoi des mails a ete correctement re-implemente seulement dans `incoming`, du coup la version stable doit encore avoir des erreurs. Cela dit, je ne pensais meme pas que l'envoi des mails fonctionnait sur la version stable...

**Comment by miton18** [comment]
j'utilise la 0.5.4

**Comment by bnjbvr** [comment]
D'accord, ce sera regle dans la prochaine version, qui devrait sortir assez rapidement, si tout se passe bien :-) Je laisse le ticket ouvert en attendant, histoire de te demander confirmation que le probleme est bien regle !

**Comment by bnjbvr** [comment]
Salut, ça devrait être réglé dans la version qui sort aujourd'hui, pourrais-tu confirmer stp, @miton18 ?

**Comment by bnjbvr** [comment]
Comme je n'ai pas eu de réponse depuis plus d'un mois, je ferme le ticket. Merci de réouvrir si le problème est toujours présent :)
