### ISSUE TITLE
adding new to transactions to an transaction (ATM debit)

### ISSUE THREAD

**Issue by dattaz** [bnjbvr/kresus#248]
For example you get some cash, you want to link this cash with transactions you made with it.
So you need to add a new transaction that corresponding to a part (or all) of my debit at ATM (and this is an transaction in kresus)

**Comment by nicofrand** [comment]
Maybe you could just set a custom label to this transaction ? https://github.com/bnjbvr/kresus/issues/217

**Comment by bnjbvr** [comment]
Thanks for the report! Am I understanding correctly that this is the same need as in #202 ?

**Comment by dattaz** [comment]
yes same as #202
