### ISSUE TITLE
Check for virtualenv's binary

### ISSUE THREAD

**Issue by babolivier** [bnjbvr/kresus#252]
On Archlinux (and, I'm sure, a few other distros), the `python` binary refers to Python 3, while the `python2` binary refers to Python 2.

The same thing goes with `virtualenv`, needed within Kresus. As the Arch package's dependencies only require `python2` (and I'm unsure about the compatibility with Python 3), when you only have this one installed and not `python`, Kresus can't find virtualenv's binary (which is problematic and prevents it to start). It's the case with current installation from the Archlinux package that don't have Python 3 installed (and I'm unsure about adding Python 3 to the dependencies by fear of breaking the app).

Now I'm wondering if Kresus supports Python 3, and, in this case, if I should add it in the package's dependencies (which would cause the user to download and install another package) or if Kresus should check if there's a `virtualenv` binary somewhere (and, if not, check if there's a `virtualenv2` it could use).

**Comment by bnjbvr** [comment]
Good points, thank you for opening an issue! I've been delaying this a bit...

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/85fc523e9cab124a60c94cf9b2fdff58b784bbc6
