### ISSUE TITLE
Add a button to toggle the search pane

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#259]
I think that it would be nice to have a button on the right side of the "Search" header to toggle the pane.

When the pane is closed, the button could be a "+", ex:

![kresus-open-searchpane](https://cloud.githubusercontent.com/assets/3419050/10966631/210742a2-83b5-11e5-91f5-db65a437e905.png)

When the pane is open, the button would become a "-", ex:

![kresus-close-searchpane1](https://cloud.githubusercontent.com/assets/3419050/10966647/39163740-83b5-11e5-8105-506334996602.png)

This would only toggle the pane visibility, not clear the form.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/29f9fd59d2ed564bf5a3fbb0580270fe50ce24ea
