### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by babolivier** [bnjbvr/kresus#268]
Since today, each time I click on the sync button on the homepage, I have an error popup. While investigating a bit, I saw that the request sent by this action got a 400 response with the following body:

```
{
  "code": "GENERIC_EXCEPTION",
  "content": ""
}
```

I also have the following in /logs/kresus:

```
[Sun, 15 Nov 2015 13:58:45 GMT] - GET /accesses/5ccf83426222d8328ca25a5504147415/fetch/operations - 400 - 347.885 ms -  41
[2015-11-15 13:59:47:546] info - sources/weboob | Fetch started: running process ./weboob/scripts/operations.sh...
[2015-11-15 13:59:47:874] info - sources/weboob | weboob exited with code 0
[2015-11-15 13:59:47:874] info - sources/weboob | weboob-stderr: Unknown error of type <class 'weboob.exceptions.BrowserSSLError'>
```

**Comment by bnjbvr** [comment]
Thanks for the report! Have you tried  updating Weboob since then? This error code refers to a generic Weboob exception, which generally means that it needs an update (or it will need one, in the next few days).

**Comment by babolivier** [comment]
Yup, just updated Weboob and retried, didn't change anything.

**Comment by ZeHiro** [comment]
It seems you're bank has updated the certs of their website. (weboob.exceptions.BrowserSSLError). Ths module should be updated soon I guess.

**Comment by silvyn** [comment]
Hi @babolivier , yes I have the same log message.

**Comment by babolivier** [comment]
The Weboob module got updated just today, allowing me to retrieve my operations again. I'll close this for now.

**Comment by silvyn** [comment]
Thanks for notice that. I've updated too, and yes it's OK :)
