### ISSUE TITLE
Do not close search form on Enter

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#275]
**Steps to reproduce:**

0. Open the transaction search form
0. Search for a label and press "enter"

**What happens:**
The form is cleared and closed

**What I expect:**
Actually, nothing: nothing should happen (the search is done in realtime for each key pressed), the form should just not be cleared/closed.

**Comment by bnjbvr** [comment]
Thank you for opening an issue.

**Comment by ZeHiro** [comment]
Just a question , should be track any button object (I think of selectable components/labels) to enforce type="button" to make sûre there is no more unexpected behaviour of this type?

**Comment by nicofrand** [comment]
Why not. We will still be able to set type="submit" when needed, that might be more clear.

**Comment by bnjbvr** [comment]
Right. Alternatively, we should wrap the button into a React component, to make sure we never do this error again. Ideally, bootstrap className should appear only in leaf components, but that's a bigger project.
