### ISSUE TITLE
Operations' label not truncated on Chrome

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#278]
When there are some really long labels, the display is kind of broken because those labels are not truncated.

On Google Chrome (latest) & Safari (7.0.4).

**Comment by ZeHiro** [comment]
Dammit! I should have tested on another browser

**Comment by nicofrand** [comment]
Me too !

**Comment by bnjbvr** [comment]
Can you test with Safari, just to make sure it isn't a Chrome-specific bug?

**Comment by bnjbvr** [comment]
Confirmed on IRC: the issue also happens with Safari.

**Comment by nicofrand** [comment]
A way to solve it on Chrome (cannot test with Safari):

* Add `table-layout: fixed` to .table (or the table we want) (that may also improve the rendering I think)
* Add `width: 30px` to the first `th` of the `.table thead`

**Comment by nicofrand** [comment]
This is now fixed.
