### ISSUE TITLE
Add a way to update weboob even with no account set

### ISSUE THREAD

**Issue by babolivier** [bnjbvr/kresus#280]
These last few days, there was a problem with Weboob preventing it to access to my bank account's data. Not knowing this at first, I installed Kresus to try it out on my self-hosted Cozy.
In the meantime, I realized the problem with Weboob on another instance I have. So I decided not to touch anything and configure Kresus on my self-hosted one once everything is back to normal.
The issue between Weboob and my bank is now solved in the latest Weboob update. On my other instance, I just updated it via the appropriate menu, and everything worked again.
When I went to do the same on my self-hosted Cozy, I stumbled upon another issue: Because I don't had any bank account configured on this one, I just can't reach the "Update Weboob" button. I think there should be some way to update it in this case.

**Comment by bnjbvr** [comment]
Thanks for opening an issue! It is indeed a problem. In the future, I plan to have a setting enabling (or disabling) automatic update of weboob every day, which would lessen the issue. However, having a nice button to update Weboob on the new bank form screen would be nice too.

Other workarounds:

- add a FakeBank account
- run the update script from the CLI: `cd kresus && ./weboob/scripts/update-modules.sh`

**Comment by ZeHiro** [comment]
Can be closed

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/d4c25235b62a8f22ca3598808630e69e5a960941
