### ISSUE TITLE
Problem to install Kresus

### ISSUE THREAD

**Issue by circark** [bnjbvr/kresus#287]
I've Cozy fresh installed on my Raspberry Pi 2. Everything run fine but i'm not able to install Kresus on it, i've constantly the same error message:

Problem to uninstall Kresus 
socket hang up : Error: socket hang up at createHangUpError (http.js:1472:15) at Socket.socketOnEnd [as onend] (http.js:1568:23) at Socket.g (events.js:180:16) at Socket.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)

any idea?

thanks!

**Comment by ZeHiro** [comment]
Hi,
installing kresus on PI2 takes a long time (compilation of weboob). You shoultd try like that in ssh:
``` sudo npm -g update cozy-monitor``` To update cozy-monitor.
Then ``` sudo cozy-monitor install kresus -r https://github.com/bnjbvr/kresus -t false```
The option t disables the tomeout for i'stallation

**Comment by bnjbvr** [comment]
Hi @circark, thank you for opening an issue. Indeed what @ZeHiro said is one possible solution; the other would be to install Weboob globally on your machine, with `apt-get install weboob` if you're using a Raspbian installation. Note that installing/updating Weboob from Kresus won't work, in this case.

**Comment by circark** [comment]
Thanks ZeHiro and bnjbvr for the quick answers. 

i tried the solution from ZeHiro with SSH and it failed too:

pi@raspberrypi ~ $ sudo cozy-monitor install kresus -r https://github.com/bnjbvr/kresus -t false
info - Install started for kresus...
error - An error occured:
error - Install failed for kresus.
[Error: Install home failed. Can't figure out the app state.]


i'll try the Weboob option but it seems a bit difficult to me, for the moment i didn't find any tutorial for Weboob + Kresus.

**Comment by ZeHiro** [comment]
Hi @circark 
HAvec you installed all the deps here : 

https://github.com/bnjbvr/kresus#on-debian

**Comment by bnjbvr** [comment]
See the new README on the `incoming` branch, it details what needs to be installed and all the extra steps. Having received no answer for more than a month, I am closing the issue. Feel free to re-open if there's something else to do.
