### ISSUE TITLE
Show needed dependencies on the load screen + make the README clearer

### ISSUE THREAD

**Issue by ArchangeGabriel** [bnjbvr/kresus#289]
See log here:
https://gist.github.com/ArchangeGabriel/2ea4bb60c609fee316d3

**Comment by bnjbvr** [comment]
Hi! You need to install Kresus dependencies, as explained in the README file: https://github.com/bnjbvr/kresus#on-any-other-unix-based-operating-system

**Comment by ArchangeGabriel** [comment]
Well, I followed the first part there: “On CozyCloud”. Maybe that only applies to CozyCloud instance, but given the proposed ways (opening a shell on the machine) I supposed this was generic and also apply to a self-hosted Cozy instance.

Also, the section your link point me at doesn’t apply, this would make Kresus as a standalone app, which is not what I want. Unless you were only talking about the dependencies part.

So, I suppose that the dependencies part also apply to Cozy. Maybe you should state it more clearly, and also have a message about this at https://github.com/bnjbvr/kresus/blob/master/client/components/LoadScreen.js ?

Thanks.

**Comment by bnjbvr** [comment]
That is right, dependencies are needed on **all** installations (CozyCloud or standalone, Debian or not). That should be made clearer in the README and in the LoadScreen as well. That's a good suggestion, thanks.

**Comment by ArchangeGabriel** [comment]
OK. Question: is it python2 or python3 dependencies that are needed? Guess python2? Are there specific version needed for other packages? (I’m running ArchLinux, and the dependencies list is quite different, since for instance they are no -dev package on this distribution).

**Comment by ArchangeGabriel** [comment]
And are python-bindings for any of the required libraries needed?

**Comment by bnjbvr** [comment]
@babolivier, can you help here please?

**Comment by babolivier** [comment]
If you installed Cozy via one of the Archlinux packages, you should have the right dependencies installed.
Kresus requires Python2. I didn't tried running the app with Python3, but there were several modules for which the installation failed at Kresus's install when using Python 3.
Concerning python-bindings, it's not required. Or if it is, it was installed by another required Python package.

**Comment by ArchangeGabriel** [comment]
Indeed, except for libyaml I’m having all the required libraries. However, it still fails. New logs here:
https://gist.github.com/ArchangeGabriel/0708fb4e175f7c7ab55e

By the way, thanks @babolivier for ArchLinux packages.

**Comment by babolivier** [comment]
My pleasure @ArchangeGabriel :)
libyaml is indeed missing in the dependencies. Thanks for noticing it, I'll update the package later (I created the issue https://github.com/babolivier/cozy-archlinux/issues/3 to remind me).

The errors seems like a package can't be installed properly because of a missing header file. Please check if `libffi` is installed on your machine.

The `python : commande introuvable` errors can be ignored, and will be fixed as soon as I finish working on #272.

**Comment by ArchangeGabriel** [comment]
```
$ yaourt -Ql libffi
libffi /usr/
libffi /usr/lib/
libffi /usr/lib/libffi-3.2.1/
libffi /usr/lib/libffi-3.2.1/include/
libffi /usr/lib/libffi-3.2.1/include/ffi.h
libffi /usr/lib/libffi-3.2.1/include/ffitarget.h
libffi /usr/lib/libffi.so
libffi /usr/lib/libffi.so.6
libffi /usr/lib/libffi.so.6.0.4
libffi /usr/lib/pkgconfig/
libffi /usr/lib/pkgconfig/libffi.pc
libffi /usr/share/
libffi /usr/share/info/
libffi /usr/share/info/libffi.info.gz
libffi /usr/share/licenses/
libffi /usr/share/licenses/libffi/
libffi /usr/share/licenses/libffi/LICENSE
libffi /usr/share/man/
libffi /usr/share/man/man3/
libffi /usr/share/man/man3/ffi.3.gz
libffi /usr/share/man/man3/ffi_call.3.gz
libffi /usr/share/man/man3/ffi_prep_cif.3.gz
libffi /usr/share/man/man3/ffi_prep_cif_var.3.gz
```

**Comment by ZeHiro** [comment]
I think you need libffi-dev (to build kresus)

**Comment by babolivier** [comment]
@ZeHiro On Archlinux, you don't have -dev packages, the base packages are the -dev (look at the paste from @ArchangeGabriel, `libffi` alone includes the dev headers).

Thanks for the paste, @ArchangeGabriel, I'll try to look into it tomorrow.

**Comment by ZeHiro** [comment]
yeah, I always forget they can (are?) compiled on the flow

**Comment by babolivier** [comment]
On the official repos, librairies aren't compiled on the flow. That only happens on AUR. What I'm trying to tell is that, on Ubuntu you usually have a "base" package with only the libraries, and a -dev package containing the .h files you can include to your program if you want to dev it with this library; but on Archlinux, you only have the dev one, containing both the library and the .h files (and that's why you usually don't find packages named "libxxx-dev" on the repos).

**Comment by ArchangeGabriel** [comment]
@babolivier Have you had the time to look at this? Thanks.

**Comment by bnjbvr** [comment]
@ArchangeGabriel, there's an open pull request about this, iirc. In the meanwhile, I've enhanced the README on incoming and linked it from the load screen.

**Comment by ArchangeGabriel** [comment]
@bnjbvr Sorry, I wasn’t talking of the initial issue but my install one (https://github.com/bnjbvr/kresus/issues/289#issuecomment-158927369 and followings). Maybe should I open a different issue?

**Comment by bnjbvr** [comment]
No problem. Feel free to comment directly on the PR that is going to solve this: https://github.com/bnjbvr/kresus/pull/272 (or if the PR isn't solving this, feel free to open a new issue). Thanks!

**Comment by ArchangeGabriel** [comment]
This PR is not solving the issue AFAIU (only removes an harmless warning here). I’m opening a new one for this, and close this one since fixed by https://github.com/bnjbvr/kresus/commit/d038d046168244499ff103937644ce4e8cb9728b.
