### ISSUE TITLE
Cannot remove a custom label

### ISSUE THREAD

**Issue by nicofrand** [bnjbvr/kresus#290]
Today I set a custom label for a transaction and then noticed I made a mistake.
I wanted to remove it by erasing the text and setting an empty custom label, but that did not work: the application does not allow to set an empty custom label when there is already one (non-empty).

**Comment by bnjbvr** [comment]
Indeed. I think you're triggering one of these conditions: https://github.com/bnjbvr/kresus/blob/incoming/client/components/OperationList.js#L181-L183
We should add an explicit way to delete a custom label, instead. We could do either "backspace twice" or have a button "delete custom label" in the detailed operation view.

**Comment by nicofrand** [comment]
Couldn't we just allow to clear the custom label field ?
If there is already a custom label, remove it (if ""), if not, do not create one.

**Comment by nicofrand** [comment]
BTW, why are there 2  listeners (onBlur + onKeyUp triggering onBlur) to do the job of one listener (onChange) which does the same thing ?

**Comment by bnjbvr** [comment]
onBlur is triggered when you leave the text field (e.g. by clicking outside the text field); onKeyUp is triggered when you press enter (code key == 13), that's why.

So emptying the custom label field would delete it, is this what you suggest? If so, it sounds fine to me.

**Comment by nicofrand** [comment]
IIRC, onChange does exactly the same thing (clicking outside and pressing enter)…
Yes, emptying the field should delete it, from a user point of view.

**Comment by ZeHiro** [comment]
The behaviour was desired, to prevent 'empy custom labels'. And nothing displayed to the user. It should be changed.

**Comment by ZeHiro** [comment]
onChange is not triggered on each change?

**Comment by nicofrand** [comment]
No, that's "input" or keypress/keyup.

**Comment by ZeHiro** [comment]
onBlur is considered as validation also?

**Comment by nicofrand** [comment]
My bad, I thought the native event was used but React onChange event is different.

**Comment by ZeHiro** [comment]
I'll take this one. 
Solution I'll implement: 
- if customLabel exists & new customLabel is empty, delete it

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/2c6c423f96402d5c0cfaff2d5083e7d14afec973
