### ISSUE TITLE
Deleting an account of a bank is not implemented

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#294]
At least client side

**Comment by ZeHiro** [comment]
Hmm nope. Only on my dev instance :p

**Comment by bnjbvr** [comment]
What if you force a refresh of the page? Maybe the icon just doesn't show up? Or try switching browsers? There might be an issue with the display of the icon. Can you check it's correctly inserted in the HTML and the correct className is getting applied?

**Comment by ZeHiro** [comment]
Opened to fast
