### ISSUE TITLE
Error raised on merg of 2 operations

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#300]
I am not sure what are the conditions which raised the error, but here is what I know.
When I merged two operations which both had "unknown  type" (but don't know if it is real "unknown type" or just "no type", an error was raised by the browser (didn't note the error, sorry).

**Comment by bnjbvr** [comment]
Thank you for opening a ticket. We might need more information or STR here :p

**Comment by ZeHiro** [comment]
I know that... But I couldn't get the exact conditions when I oppened the ticket. I'll try to reproduce on my dev instance.

**Comment by ZeHiro** [comment]
OK. I didn't reproduce, but on reading the code, I understood what happened: 
- Merge 2 operations with no operation type set.
- Here: https://github.com/bnjbvr/kresus/blob/incoming/client/store.js#L575
- The type is not set to the unknownTypeID, then the error was raised.

**Comment by bnjbvr** [comment]
Good catch. I'll take care of fixing this; we shouldn't just apply the unknown operation type afterwards, but make sure that creating an operation does it for us. Also, there's a discrepancy between the naming of types, `type` and `operationTypeId`, which is at fault here.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/c6441b3e0990fad7a556b845983bcb136375e9cf .

If you have the opportunity, can you test and confirm, please?
