### ISSUE TITLE
Kresus fails to install on a ArchLinux based Cozy

### ISSUE THREAD

**Issue by ArchangeGabriel** [bnjbvr/kresus#301]
Continuation of https://github.com/bnjbvr/kresus/issues/289

Logs: https://gist.github.com/ArchangeGabriel/0708fb4e175f7c7ab55e

libffi is installed:
```
$ yaourt -Ql libffi
libffi /usr/
libffi /usr/lib/
libffi /usr/lib/libffi-3.2.1/
libffi /usr/lib/libffi-3.2.1/include/
libffi /usr/lib/libffi-3.2.1/include/ffi.h
libffi /usr/lib/libffi-3.2.1/include/ffitarget.h
libffi /usr/lib/libffi.so
libffi /usr/lib/libffi.so.6
libffi /usr/lib/libffi.so.6.0.4
libffi /usr/lib/pkgconfig/
libffi /usr/lib/pkgconfig/libffi.pc
libffi /usr/share/
libffi /usr/share/info/
libffi /usr/share/info/libffi.info.gz
libffi /usr/share/licenses/
libffi /usr/share/licenses/libffi/
libffi /usr/share/licenses/libffi/LICENSE
libffi /usr/share/man/
libffi /usr/share/man/man3/
libffi /usr/share/man/man3/ffi.3.gz
libffi /usr/share/man/man3/ffi_call.3.gz
libffi /usr/share/man/man3/ffi_prep_cif.3.gz
libffi /usr/share/man/man3/ffi_prep_cif_var.3.gz
```

CC @babolivier.

**Comment by babolivier** [comment]
Hi @ArchangeGabriel 

I'm really, really sorry about the delay. The hosting company from which I rent my test servers had an IP avalability failure (so I couldn't investigate the issue), and I'm currently working on the new infrastructure of an organisation I'm part of, so I'm really not sure about when I'll be able to get back on this issue. But I will, for sure.

**Comment by ArchangeGabriel** [comment]
OK, no problem.

**Comment by ArchangeGabriel** [comment]
It works now. Not sure if it’s a change in Kresus/Cozy or python2-cffi upgrade (or even something else).
