### ISSUE TITLE
Deleting the default account will trigger an error

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#302]
STR:
- set an account as a default account
- delete it from the preferences
- reload page

So this has to be done on the server: when deleting an account, check if it is the default account and remove the default account value in that case.

@nicofrand, willing to fix this?

**Comment by nicofrand** [comment]
Yep, will do !

**Comment by bnjbvr** [comment]
Cheers!

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/1d90b13437b8efe49bd6ab3450b33eb708fb37f1
