### ISSUE TITLE
On deletion of the last account of a bank, the bank is still displayed on the client

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#306]
Go to settings
Delete the last account of a bank

What is expected: 
- the bank is not shown anymore on the client

What I see: 
- the bank is still displayed.

On reload of the app, the bank is not displayed anymore.

Also, a request "GET /accounts/accountID" is thrown just after the deletion. (accountID being the data-system ID of the deleted account)

**Comment by bnjbvr** [comment]
Thank you for opening an issue.

**Comment by ZeHiro** [comment]
can be closed

**Comment by bnjbvr** [comment]
Fixed by https://github.com/ZeHiro/kresus/commit/cc671520592682e2b8dc3e125f659ba2f4af3f42
