### ISSUE TITLE
When two accounts have the same number (accountNumber) an error is raised when trying to set an email Alert

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#308]
To reproduce : 
create Frake Bank 1 and 2. Go to settings / Emails. The raised error is: 
```
Assertion error: accountNumber should be globally unique
```

**Comment by ZeHiro** [comment]
This error is normal :p, maybe shall we update the Fake banks, so that they don't have the same account numbers

**Comment by bnjbvr** [comment]
Indeed, thanks for opening an issue.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/d2114a3c7158ee4627113178155274f206d86b8f
