### ISSUE TITLE
Today's operations are not displayed on balance chart

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#322]
When an operation has date = Today, it is not diplayed on balance chart.

**Comment by bnjbvr** [comment]
Indeed, thanks for opening an issue.

**Comment by bnjbvr** [comment]
@ZeHiro, can you please confirm this is fixed on incoming? (if so, feel free to close the issue)

**Comment by ZeHiro** [comment]
@bnjbvr : fixed.

**Comment by ZeHiro** [comment]
@bnjbvr : In fact, today's operations are displayed, but not future operations. The scale goes to the date of future date, but it is not plotted

**Comment by bnjbvr** [comment]
Sounds fine to me, at the moment: this could be handled in #310.
