### ISSUE TITLE
In search operations wrong selection of catgory/type when toggling on and off search operation

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#328]
To reproduce: 
- Show search operations panel
- Filter operations by category or type
- Hide search operation panel
- Show search operation panel

Observed: 
- The value in the select is "any category/type"

Expected: 
- The value in the select should be the one selected before hiding/showing again panel

Moreover, it is impossible to show again all the operations as there is no change in the select (need to select another category/type and then select 'any category/type'

**Comment by bnjbvr** [comment]
Good catch!

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/4dad8903629720d2c15f9ccd0ba9b7032ae6ba09 .
