### ISSUE TITLE
Spawning sh weboob's scripts causes [execvp(): Permission denied]

### ISSUE THREAD

**Issue by PandiPanda69** [bnjbvr/kresus#333]
Hey !

I had a little issue when trying to install Kresus on a Debian Jessie. The root cause seems to come from the code, i'll give more details about it later.

First, to be sure I did it the right way, here what I did:
1- make install-debian-deps (*notice it could be improved by adding an apt-get upgrade*)
2- install weboob (v1.1)
3- make build
4- make run

Following those steps, right after log entry "init | Success: All banks added.", spawn fails and process exits: Error: spawn EACCES.

I debugged a bit to look what exactly happened and, in `server/lib/sources/weboob.js:89` I found shell scripts were called this way:
```javascript
let script = spawn('./weboob/scripts/test.sh');
```

Unfortunately, CWD is set to `/foo/build/server/lib/sources` when running the app and thus, `/foo/build/server/lib/sources/weboob/scripts/test.sh` cannot be found.

Maybe I did something wrong when installing the app, if so maybe could I get a little help :-)

**Comment by bnjbvr** [comment]
Thanks for the detailed issue! Can you confirm whether https://github.com/bnjbvr/kresus/commit/e8fec4422d9ae1c48eefe1a283bbf1c5db23e721 fixed it?

**Comment by PandiPanda69** [comment]
Thank you very much for the fix.

It works like a charm now !

**Comment by bnjbvr** [comment]
Thanks for confirming, closing the issue.
