### ISSUE TITLE
CreateOperationModal should show the account's title, not the account's bank id

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#341]

**Comment by ZeHiro** [comment]
got it

**Comment by ZeHiro** [comment]
To also do:
creating an operation should also emit State.Operations
use defalutValue instad of selected
add key= to select components

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/fea81d5d40bb6cbb98b43eb325aaf1093648e905
