### ISSUE TITLE
Allow to activate debug mode for weboob

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#363]
A user from weboob IRC channel suggest it could be interesting to be able to activate debug mode for weboob from the WEBUI, it would help to debug module problems.

An idea could be to override the default logger of Weboob instance in Conector class.

Example from weboob IRC chan : 
https://linuxfr.org/nodes/108182/comments/1644108

**Comment by ZeHiro** [comment]
@bnjbvr, can we consider this fixed by 0d98cc5 ?

**Comment by bnjbvr** [comment]
No, this isn't quite the same. Weboob debug logs might be even more helpful.

**Comment by bnjbvr** [comment]
Fixed by a6921ca
