### ISSUE TITLE
Opération manquante

### ISSUE THREAD

**Issue by ArchangeGabriel** [bnjbvr/kresus#373]
Je viens de m’apercevoir qu’il manque une opération dans mes comptes.

Je pense que Kresus l’a fautivement détectée comme doublon tout seul alors que ça n’en est pas un : en effet, j’ai fait deux paiement, du même montant, au même service, le même jour. Seul l’un des deux apparaît.

**Comment by bnjbvr** [comment]
Merci pour le rapport de bug ! Bizarrement, plein de gens ont commencé à avoir ce bug à peu près en même temps, moi y compris. Par conséquent, ça va être réglé très rapidement... En attendant, tu peux ajouter l'opération à la main en allant dans les préférences puis en cliquant sur le + à côté du nom du compte, puis en renseignant toutes les informations, mais c'est un brin fastidieux...

**Comment by ZeHiro** [comment]
Même problème que #209. 
Devrait être corrigé avec #379

**Comment by bnjbvr** [comment]
Corrigé par https://github.com/bnjbvr/kresus/pull/379/commits/d30f948b0486d03040b09bd9eccf42916389afa2, sera dans la prochaine version. Merci encore pour le retour !
