### ISSUE TITLE
Fail to build weboob within an OVH VPS

### ISSUE THREAD

**Issue by encolpe** [bnjbvr/kresus#381]
I'm testing the OVH images of cozycloud and it fails on kresus installation.

On this configuration neither the python-weboob package nor the dependencies to build it are installed by default.

If I install the python-weboob package the kresus installer fail to find it and try to build weboob. 

If I go in `/usr/local/cozy/apps/kresus` and run `make install-debian-deps` it finally works.

**Comment by bnjbvr** [comment]
Thank you for the report! That being said, there's not much we can do here: I don't have control on the OVH VPS images. Next version of Weboob will just need `python-weboob` or `python-weboob-core` to be installed, and there will be a message saying that if Weboob can't be run by the Kresus user.

I don't think there is much we can do here, so closing. In the meanwhile, let's @nledez know about this issue, maybe he can help here.
