### ISSUE TITLE
Send email when INVALID_PASSWORD is raised

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#397]
So that accounts are not blocked.

**Comment by ZeHiro** [comment]
even better management could be to save this error in the DB, and stop automatic fetching if last import resulted in INVALID_PASSWORD

**Comment by bnjbvr** [comment]
Nice idea. It introduces a bit of complexity, though: you want to be able to restart automatic polling as soon as the password has been replaced (or another manual polling worked again): so the polling has to share state with external units, in particular other files should be able to call in the poller to restart it, without introducing too much complexity.

**Comment by ZeHiro** [comment]
I was thinking of testing the lastFetch status before actually fethcing, without restarting the poller. First of all, the poller needs to continue fetching on error, but I'm working on it.
The status needs also to be updated on manual fetching.

**Comment by bnjbvr** [comment]
Closed by  44f0f8b. Thanks ZeHiro!
