### ISSUE TITLE
Show type of transaction

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#40]
HEllo,

It could be use full to see the type of transaction in the "Report" page.

Thank you

**Comment by bnjbvr** [comment]
That'd be great! I'll try to find if I can retrieve this information from the weboob backend...

**Comment by bnjbvr** [comment]
That's actually in weboob! I'll add that in a next version later.

**Comment by ZeHiro** [comment]
I have looked to json bankoob output, the type of transaction is under the attribute "type" (long). 
0 -> Default/No type defined
1 -> TRqnsfert from the qccount
2 -> Prélevement
6 -> Cash Withdraw
7 -> Card Payment (Debit)
9 -> Bank costs (not interests)

I miss : chèque IN et chèque OUT, virement.
But I am not sure it is "standard" as I only checked on one account

**Comment by ZeHiro** [comment]
From other account : 
1-> Transfer from OR to the account
3 -> Chèque OUT

**Comment by bnjbvr** [comment]
Ha nice, thanks for finding these constants.

**Comment by ZeHiro** [comment]
Hi,

I have patched kresus to import the operation type in th DB. But I have one question, currently, I have imported the "number value". Do you think it is better to import a textual value for the type or I keep the number value?

**Comment by bnjbvr** [comment]
I'd really prefer the text value, to avoid indirections as much as possible. Thanks for working on it!

**Comment by ZeHiro** [comment]
Then I'll use the textual value. 
I had included the feature by just modifying a few lines (server side) in the whole code, but at the end, it won't allow me to do what I want to do with it. As the transactions are detected through regexps by weboob, sometimes they are wrong. So I want to add the possibility to manually modify the transaction, and update it in the couchDB (not for now, I start with display in kresus). To achieve this, I need to be able to transfer all the possible values to the client, so I plan to add a new   type of information (OperationType or something like that), like the list of supported banks. Does it look good to you?

**Comment by bnjbvr** [comment]
Sounds perfect! I propose you the following plan (one bullet per commit, ideally):

1. extract transaction type information from weboob
2. show transaction type in the client
3. allow modifying the transaction type in the client

Let me know if I can help you in any way :)

**Comment by ZeHiro** [comment]
Hi,

I have a version which works for the import of types (some default cases stil have to be tested) . It works fine, but I have doubts due to async steps. Could you check the code? 
My major doubt is here :  

https://github.com/ZeHiro/kresus/blob/master/server/lib/weboob-manager.coffee#L102

I fear that if calling  OperationType.getOperationName method is to long, the operationType will not be included in the "operation" 
Should I move this call later in the process? Like 
create a new me thod processOperationType which is called before processRetrievedOperation

**Comment by bnjbvr** [comment]
Nice work done on that! Skimming at your code, if I've understood correctly, the following is happening:

1. you have a file with the number/name mappings in a JSON file.
2. you read this file at startup and add the pairs to the DB if needed.
3. when adding an operation, you try to retrieve the name of the operation type by looking up the name in the DB.

JS is such that the variable called `operation` is a reference to the object itself, so even if the operation is added to the array before the operation type is retrieved, the operation type might be likely be found in the meanwhile. However, there's a race condition: do we find the operation type first, or do we save the operation first?

To avoid this issue, here's what I recommend:

- in addition to saving the pairs, in step 2, you can use a plain object as a map in the OperationType model, that keeps the pairs in memory (that is an object whose keys are the weboob number and whose values are the associated text). The number of pairs is small enough that we don't care about the implied memory usage of this map.
- in step 3, you can just retrieve the text value synchronously with this map.

How does that sound?

**Comment by ZeHiro** [comment]
You understood what I did. 
And the solution looks good. I'll try to implement this.

**Comment by bnjbvr** [comment]
That work you've done in previous PR, thanks!
