### ISSUE TITLE
master key and slave key don't exist

### ISSUE THREAD

**Issue by jeekajoo** [bnjbvr/kresus#403]
Hi,
I have this errors in data-system logs:
```
[2016-04-26 10:31:04:435] info - helper/db_feed | Publishing usage.application kresus
error - lib/encryption | [decrypt]: master key and slave key don't exist
error - lib/encryption | [decrypt]: master key and slave key don't exist
error - lib/encryption | [decrypt]: master key and slave key don't exist
error - lib/encryption | [decrypt]: master key and slave key don't exist
```
Still, kresus works properly.
Thanks

J.

**Comment by ZeHiro** [comment]
This problem really looks like a cozy plateform problem. If you restart the datasystem /proxy this will work again.

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Yeah, it really is a problem from the platform itself, so unless you think about something else in particular, which impacts how kresus works, I don't think there's much to do from our side. Feel free to reopen though ;)
