### ISSUE TITLE
Caisse d'Épargne Weboob error: Invalid literal for Decimal

### ISSUE THREAD

**Issue by pbernery** [bnjbvr/kresus#408]
Salut,

Je viens d'essayer Kresus (via Cozy) and ça semble prometteur.

J'ai cependant une erreur (je l'ai d'abord rapporté [ici](https://forum.cozy.io/t/apps-kresus-unknown-error-of-weboob/2415/1) mais je pense que ce n'est pas le bon endroit)

Quand je tente d'ajouter un compte de la Caisse d'Épargne Ile-de-France, j'ai une erreur affichée dans une popup : "Erreur inattendue: undefined".

Voici les logs correspondants :
```
[2016-04-30 20:59:09:593] info - sources/weboob | Fetch started: running process ./weboob/scripts/accounts.sh...
[2016-04-30 20:59:13:655] info - sources/weboob | weboob exited with code 0
[2016-04-30 20:59:13:656] info - sources/weboob | stderr: Unknown error of type <class 'decimal.InvalidOperation'>

[2016-04-30 20:59:13:657] info - controllers/accesses | 	deleting access...
[2016-04-30 20:59:13:656] warn - sources/weboob | Weboob error, stderr: Unknown error of type <class 'decimal.InvalidOperation'>

[2016-04-30 20:59:13:657] error - controllers/accesses | The access process creation failed, cleaning up...
[2016-04-30 20:59:13:690] warn - helpers | no status in asyncErr
[2016-04-30 20:59:13:691] error - helpers | Error: when creating a bank access: [object Object] - when creating a bank access: Invalid literal for Decimal: ''
[Sat, 30 Apr 2016 18:59:13 GMT] - POST /accesses/ - 500 - 4866.257 ms -  101
```

J'ai réussi à ajouter un compte de La Banque Postale et un compte de la Caisse d'Épargne Bretagne, bien que pour ce dernier cela ne fonctionnait pas hier, et en redémarrant Kresus aujourd'hui il est apparu.

Une idée ?

**Comment by bnjbvr** [comment]
Salut, merci pour le rapport d'erreur ! C'est un problème dans Weboob (le sous système qui se connecte au site de banque), qui reçoit des données qui n'ont pas la forme attendue.

Es-tu hébergé par CozyCloud ou auto-hébergé ? Dans le second cas, on pourrait essayer la version bêta de Kresus qui devrait nous donner plus d'informations sur l'erreur rencontrée dans Weboob.

Aussi, pourrais-tu essayer avec l'application en CLI boobank, qui s'installe avec le paquet Weboob dans Debian/Ubuntu? (pour les autres distros, voir http://weboob.org/install ). Si l'erreur se reproduit avec boobank, alors c'est un souci à régler du côté de Weboob.

Merci !

**Comment by pbernery** [comment]
Merci pour la réponse.

Je suis auto-hébergé (Debian 8), je vais donc pouvoir essayer la version
beta, et j'essaierai avant Boobank pour voir si j'ai le même résultat.

Je devrais pouvoir le faire dans la semaine mais pas avant quelques jours.
Je donnerai des nouvelles !
Le lun. 2 mai 2016 à 09:19, Benjamin Bouvier <notifications@github.com> a
écrit :

**Comment by pbernery** [comment]
Salut @bnjbvr,

Je viens d'essayer boobank provenant de la version de weboob installée avec Debian et j'ai eu une erreur SSL. En regardant sur le net, j'ai vu que ça pouvait être dû à une différence entre la base de certificats de boobank et le site. 
En essayant la version devel (branche devel indiquée sur ce site : http://weboob.org/install), je n'ai plus le soucis de SSL mais je retombe sur l'erreur vue dans Kresus : `Bug(caissedepargne): Invalid literal for Decimal: ''`.

J'ai voulu remonter le bug sur Weboob mais je vois qu'il est déjà déclaré :) : https://symlink.me/issues/2622

Si personne ne prend la main, je jetterai un œil je pense.

**Comment by bnjbvr** [comment]
Super, merci du retour ! Je laisse ouvert pour confirmer que c'est bien côté weboob d'ici à ce qu'ils fassent la mise à jour :-)

**Comment by pbernery** [comment]
Ils vont vite ! Le problème a été corrigé dans la branche devel. Je ne sais pas trop de quelle manière ils publient des versions stables ensuite.
Est-ce que c'est possible d'utiliser la branche devel sur Kresus facilement ?

**Comment by bnjbvr** [comment]
Salut ! Si tu utilises la version release (sur master), tu devrais pouvoir mettre à jour les modules depuis l'administration de Weboob (dans les préférences), à partir du moment où ils effectuent un "backport" du module. Ou sinon réinstaller Weboob.

Dans la prochaine version, où Weboob sera utilisé globalement, tu pourras utiliser la version de ton choix comme tu le souhaites ;)

Je ferme le ticket, je ne pense pas qu'il y ait quoi que ce soit à faire du côté de Kresus. La seule chose à laquelle j'aurais pu penser aurait été un mode pour passer sur la branche devel de weboob, mais au vu du fonctionnement de la prochaine version, ce serait beaucoup de travail annulé dans peu de temps, donc peu de valeur à long terme. Merci du retour !

**Comment by pbernery** [comment]
Je viens de mettre à jour Weboob via l'interface de Kresus et c'est bon, ça fonctionne ! Merci pour l'aide.

Je viens de voir 2 points par contre, j'ai créé des tickets pour chacun :

- [Mélange de compte](https://github.com/bnjbvr/kresus/issues/416)
- [Dédoublement en trop ?](https://github.com/bnjbvr/kresus/issues/417)
