### ISSUE TITLE
Manage the case when the weboob module imports operations prior to the first import

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#413]
seen on IRC : 
 Petit soucis avec Kresus, j'ai plein de nouvelles opérations qui ont été importée datant de l'année dernière (normalement, non accessible depuis l'interface web de ma banque). Je parle de la BNP.

The balance is then not correct at all.

**Comment by ZeHiro** [comment]
maybe a duplicate of #141

**Comment by bnjbvr** [comment]
Thanks. I am thinking about this possible solution: each accounts gets a new field "oldest-operation" which is filled with the account's first import date. Each time we import transactions, we sum up the amount of transactions older than the oldest-operation, subtract this from the account's balance, update the oldest-operation. That should do it.

**Comment by ZeHiro** [comment]
I think so. We just need to manage a clean transition. Including account with no operation for this oldest-operation field.

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/f6b7f8247759d73ad16de1f13b104df5452ea385
