### ISSUE TITLE
Dédoublement d'opérations en trop ?

### ISSUE THREAD

**Issue by pbernery** [bnjbvr/kresus#417]
J'ai un compte (La Banque Postale) qui a reçu 2 opérations du même montant et du même nom le même jour (2 retraits de 20€).

Dans Kresus, je ne vois qu'une opération. Est-ce que ce serait dû à un dédoublement automatique en trop (si cela existe) ? Ou est-ce que c'est simplement La Banque Postale qui n'a pas vraiment inclue l'opération encore (opération à venir) ?

**Comment by ArchangeGabriel** [comment]
C’est un bug connu : https://github.com/bnjbvr/kresus/issues/373.

**Comment by ZeHiro** [comment]
@ArchangeGabriel, ce probleme est connu et corrigé dans la prochaine version prévue si tout se passe bien dans un mois. Pour corriger ça tu ppeux passer par preferences et tu peux ajouter manuellement l'opération via le + a coté du compte

**Comment by pbernery** [comment]
C'est noté, merci pour vos retours

**Comment by bnjbvr** [comment]
Corrigé dans https://github.com/bnjbvr/kresus/pull/379/commits/d30f948b0486d03040b09bd9eccf42916389afa2, sera dans la prochaine version. Merci encore pour le retour !
