### ISSUE TITLE
Problem with account update, with no update

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#48]
Hello,

when I connect to kresus, an update of my bank account is done (LCL account)

127.0.0.1 - GET /banks HTTP/1.1 200 5870 - 236 ms
127.0.0.1 - GET /categories HTTP/1.1 200 2 - 157 ms
127.0.0.1 - GET /banks?withAccountOnly=true HTTP/1.1 200 69 - 229 ms
127.0.0.1 - GET /banks/getAccounts/ef60d9f670c6c0d57ba2999a4e004cc5 HTTP/1.1 200 246 - 231 ms
127.0.0.1 - GET /accounts/getOperations/ef60d9f670c6c0d57ba2999a4e010176 HTTP/1.1 200 18668 - 209 ms
127.0.0.1 - GET /accounts/getOperations/ef60d9f670c6c0d57ba2999a4e010176 HTTP/1.1 304 - - 214 ms

In this situation, the account does not need any update (HTTP 304 returned).
But if I click on the "synchronize now" button, I get a popup with : 
xhr error: error
Internal Server Error

And here is the log : 

Weboob is not available -- null
127.0.0.1 - GET /accounts/retrieveOperations/ef60d9f670c6c0d57ba2999a4e010176 HTTP/1.1 500 90 - 133 ms

It looks like weboob is not release propperly when 304 answer is sent.

**Comment by bnjbvr** [comment]
Hi! I'm planning to release a new version of kresus which should hopefully solve this issue. When it's out, you'll get a notification for updating kresus, and hopefully we should have more debugging tool. Hopefully, this could be an issue I've solved when importing weboob into kresus...

**Comment by ZeHiro** [comment]
OK. I'll come back with comments after the update

**Comment by bnjbvr** [comment]
Hey, can you try with the updated version, please?

**Comment by ZeHiro** [comment]
I tried to update this morning, and the update didn't go well. I'll try to post logs tonight, but I cannot promise I'll have time. If I remember well, dowloading weboob each time is to long

**Comment by bnjbvr** [comment]
Hi ZeHiro, could you try updating Kresus and trying again, please?

**Comment by ZeHiro** [comment]
OK. I just restarted ;y cozy, so weboob is still resinstalling. And on the PI2, it takes its time. I update the ticket asap.

**Comment by ZeHiro** [comment]
fixed. can be closed

**Comment by bnjbvr** [comment]
Cool, thank you!
