### ISSUE TITLE
Problem at first launch of kresus

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#51]
COzy is installed on Raspberry Pi
Kresus version is 0.4.2

Here is the display on the web browser : 

Is it installed?
Installing...
[install.sh] -- New python executable in env/bin/python
Installing setuptools, pip...
[install.sh] -- done.

[install.sh] -- Collecting git+git://git.symlink.me/pub/romain/weboob (from -r requirements.txt (line 1))

[install.sh] --   Cloning git://git.symlink.me/pub/romain/weboob to /tmp/pip-GkkOGQ-build

[install.sh] -- Collecting git+git://git.symlink.me/pub/weboob/modules (from -r requirements.txt (line 2))

[install.sh] --   Cloning git://git.symlink.me/pub/weboob/modules to /tmp/pip-aQrqYe-build

[install.sh] --     /usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/setuptools/dist.py:292: UserWarning: The version specified ('0.h') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

[install.sh] --       "details." % self.metadata.version

[install.sh] -- Collecting cssselect (from -r requirements.txt (line 3))

[install.sh] --   Downloading cssselect-0.9.1.tar.gz

[install.sh] -- Collecting lxml (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading lxml-3.4.2.tar.gz (3.5MB)

[install.sh] --     /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'

[install.sh] --       warnings.warn(msg)
    Building lxml version 3.4.2.
    Building without Cython.
    Using build configuration of libxslt 1.1.26

[install.sh] --     Building against libxml2/libxslt in the following directory: /usr/lib

[install.sh] -- Collecting feedparser (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading feedparser-5.1.3.tar.bz2 (202kB)

[install.sh] -- Collecting requests (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading requests-2.6.0-py2.py3-none-any.whl (469kB)

[install.sh] -- Collecting python-dateutil (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading python_dateutil-2.4.1-py2.py3-none-any.whl (188kB)

[install.sh] -- Collecting PyYAML (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading PyYAML-3.11.tar.gz (248kB)

[install.sh] -- Collecting prettytable (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading prettytable-0.7.2.tar.bz2

[install.sh] -- Collecting Pillow (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading Pillow-2.7.0.tar.gz (7.4MB)

[install.sh] -- Collecting gdata (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading gdata-2.0.18.tar.gz (2.5MB)

[install.sh] -- Collecting mechanize (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading mechanize-0.2.5.tar.gz (383kB)

[install.sh] -- Collecting futures (from weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading futures-2.2.0-py2.py3-none-any.whl

[install.sh] -- Collecting six>=1.5 (from python-dateutil->weboob==1.1->-r requirements.txt (line 1))

[install.sh] --   Downloading six-1.9.0-py2.py3-none-any.whl

[install.sh] -- Installing collected packages: six, weboob-modules, weboob, futures, mechanize, gdata, Pillow, prettytable, PyYAML, python-dateutil, requests, feedparser, lxml, cssselect

[install.sh] -- 

[install.sh] --   Running setup.py install for weboob-modules

[install.sh] --     /usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/setuptools/dist.py:292: UserWarning: The version specified ('0.h') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

[install.sh] --       "details." % self.metadata.version

[install.sh] --     /usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'weboob-modules (0.h)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.

[install.sh] --       PEP440Warning,

[install.sh] --   Running setup.py install for weboob

[install.sh] --     changing mode of build/scripts-2.7/weboob-config from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/weboob-repos from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/weboob-debug from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/boobathon from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/galleroob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/suboob from 644 to 755
    changing mode of build/scripts-2.7/wetboobs from 644 to 755
    changing mode of build/scripts-2.7/boobank from 644 to 755
    changing mode of build/scripts-2.7/webcontentedit from 644 to 755
    changing mode of build/scripts-2.7/traveloob from 644 to 755
    changing mode of build/scripts-2.7/boobtracker from 644 to 755
    changing mode of build/scripts-2.7/monboob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/handjoob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/translaboob from 644 to 755
    changing mode of build/scripts-2.7/videoob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/flatboob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/radioob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/geolooc from 644 to 755
    changing mode of build/scripts-2.7/weboob-cli from 644 to 755
    changing mode of build/scripts-2.7/parceloob from 644 to 755
    changing mode of build/scripts-2.7/cineoob from 644 to 755
    changing mode of build/scripts-2.7/boobmsg from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/boobill from 644 to 755
    changing mode of build/scripts-2.7/boobcoming from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/pastoob from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/boobsize from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/boobooks from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/comparoob from 644 to 755
    changing mode of build/scripts-2.7/booblyrics from 644 to 755
    changing mode of build/scripts-2.7/cookboob from 644 to 755
    changing mode of build/scripts-2.7/weboorrents from 644 to 755

[install.sh] --     changing mode of build/scripts-2.7/shopoob from 644 to 755
    changing mode of build/scripts-2.7/havedate from 644 to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/radioob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/weboob-cli to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobsize to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/cineoob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobtracker to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/handjoob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/geolooc to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/translaboob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/weboob-debug to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobooks to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/cookboob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/webcontentedit to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobcoming to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/weboob-repos to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/booblyrics to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/monboob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/wetboobs to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/pastoob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/traveloob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/videoob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobill to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/parceloob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/flatboob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobank to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/havedate to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/weboob-config to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/suboob to 755

[install.sh] --     changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/shopoob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/galleroob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobathon to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/comparoob to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/weboorrents to 755
    changing mode of /usr/local/cozy/apps/kresus/weboob/env/bin/boobmsg to 755

[install.sh] -- 

[install.sh] --   Running setup.py install for mechanize

[install.sh] --   Running setup.py install for gdata

[install.sh] --   Running setup.py install for Pillow

Rights problem ???

**Comment by bnjbvr** [comment]
Hi @ZeHiro , could you please update Kresus and try again? Now Kresus will try to reinstall itself 3 times, if it fails the first two times, hopefully that should be enough, because it's not clear what's going wrong here.

**Comment by ZeHiro** [comment]
Hi, weboob just takes a loooooong time to install on the RPI2. I just restarted the cozy, so it is still being reinstalled. But the ticket coulb be closed, as it finally works, but a few hours later

**Comment by bnjbvr** [comment]
Cool, thanks for letting me know!
