### ISSUE TITLE
Define a favorite bank/account pair

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/kresus#55]
This has been requested several times and I understand how this can be useful.

**Comment by ZeHiro** [comment]
Another enhancement would be to allow to set a "default account" : this would be the one displayed by default when launching kresus, instead of the first account of the first bank in alphabetical order.

**Comment by marienfressinaud** [comment]
That would be an essential feature for me :heart_eyes: if you consider https://github.com/bnjbvr/kresus/issues/103, you understand it's almost unusable on tablet or mobile :(

**Comment by nicofrand** [comment]
I'd like to work on it, if you are not in a hurry.

**What I'd like to propose:**

In the settings panel, under "Bank accounts" I'd like to add a button (a star icon) on the left of the remove button.

![kresus-default-account](https://cloud.githubusercontent.com/assets/3419050/11057925/859dc8f2-878f-11e5-9884-75f1aa1983c8.png)

Clicking on this star would set this account from this bank as the default, ie. the bank which this account is part of would be displayed by default and this account in particular would be displayed.

**Comment by ZeHiro** [comment]
@nicofrand Nice. 
How would be displayed the "default account"?

**Comment by nicofrand** [comment]
I thought the star icon would simply be hidden but maybe I could change the line background color or something. 

Do you have something in mind ?

**Comment by ZeHiro** [comment]
I didn't see the last part or your proposal ;).
Maybe in left the column the display could be this way : 
- First bank : Bank of starred account
 - First account: starred account
 - other Account classified by alphabetical order
- other banks classified by alphabetical order
 - accounts clssified by by alphabetical order

**Comment by nicofrand** [comment]
Oh you meant in the account list ?
I was simply speaking about the settings.

I did not think about modifying the account list at all. The account list sorting is clearer the way it is (lexical) in my opinion. 

The true need is "When I open Kresus I want this account from this bank to be displayed by default, not the first account of the first bank, according to the lexical order".

**Comment by ZeHiro** [comment]
OK, then it's good :)

**Comment by bnjbvr** [comment]
Sounds good. About the UX, how about:
- having the star icon be on the left?
- having the star just be an icon, not a button? And when it's selected, the icon changes color (from black to yellow).

For the implementation, it would make sense that the favorite account be a KresusConfig (name: "favoriteAccountId", value: id of the account), rather than a property of the account. This way, we don't have to worry that there are several favorite accounts. It implies that you'll need to go through the list of banks to find in which bank is the account, but that sounds fine; I don't think there might be more than 10 banks / 30 accounts on a single instance.

**Comment by nicofrand** [comment]
I'm OK with the icon on the left and the color.

For the implementation I thought of setting it in the settings/config yes, I still need to see with you on IRC how to do it though :).

**Comment by bnjbvr** [comment]
Fixed by https://github.com/bnjbvr/kresus/commit/b06f09cfabc5cf5a6b780d292daac7f5fa1cccc9
