### ISSUE TITLE
Use Cozy UI

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#56]
Hi,
The interface of Kresus does us the "default" cozy UI. Once Kresus is launched, it is not possible to reselect another APP, like in the default cozy UI.

**Comment by bnjbvr** [comment]
Not sure what you're referring to: is it that the top bar is disappearing? If so, I can't reproduce it locally... What browser do you use?

**Comment by ZeHiro** [comment]
Yes. I am using firefox 36.0.4 for fedora x64

**Comment by bnjbvr** [comment]
Can't reproduce locally with Firefox 40. Could you please give me a list of steps to reproduce, from a fresh start on your cozy instance (i.e. step one would be "open a tab with cozy"), please?

**Comment by ZeHiro** [comment]
Couldn'r reproduce also. Can be closed

**Comment by bnjbvr** [comment]
Thanks for letting me know!

**Comment by ZeHiro** [comment]
With pleasure, I really had problem to build weboob (when the page is reloaded during install, next installs fail when building lxml)
