### ISSUE TITLE
The app works, but old data is showed

### ISSUE THREAD

**Issue by adeleglise** [bnjbvr/kresus#57]
Hi,

I've updated the app (now using 0.4.3) and I can connect to my account.

But all the data in the app are from 2014, the synchronization works with no errors.

**Comment by bnjbvr** [comment]
Hi,

That is strange.

- Was it already the case with the previous version of kresus, or is it new?
- When you connect to your bank website, do you only see old data from 2014?
- When you say you're seeing data from 2014 only, in which section are you browsing? (list of transactions, charts, etc.)
- Can you spot something weird in the server log, when doing the synchronization?
- Can you spot something weird in the developers console, when launching the app (in particular, make sure to force reload with Ctrl F5)?

**Comment by bnjbvr** [comment]
Any news, @adeleglise ?

**Comment by adeleglise** [comment]
Hi bnjbvr, I'm sorry I can't give a feedback for now. I will try to do it this week.

**Comment by nicofrand** [comment]
This was probably a duplicate of https://github.com/bnjbvr/kresus/issues/150 ?

**Comment by bnjbvr** [comment]
Any news here, @adeleglise ?

**Comment by bnjbvr** [comment]
No answer since May 4th, closing. Feel free to reopen if the issue is still present nowadays.
