### ISSUE TITLE
Readme: add firewall recommendations

### ISSUE THREAD

**Issue by 0liUms** [bnjbvr/kresus#59]
Hi,
when i launch kresus it stand on "charging dependencies" ( with fake unicorn video ) and don't show any log in the window reserved ( toggle log button )
In the web console I get this error : 
Error: Permission denied to access property "toString"

And others warnings http://pastebin.com/SejX9EWR

Any idea ?

**Comment by bnjbvr** [comment]
Oops! I made a mistake with the log console, which should be fixed as of now in the incoming branch. I will let you know when I bump the version so that you can try in the latest stable version.

**Comment by bnjbvr** [comment]
Hi @0liUms, could you please retry with the latest updated version of kresus?

**Comment by 0liUms** [comment]
I i try using the latest - 0.4.4

Now I got it in the log window :


    Is it installed?
    => No it isn't. Installing weboob...
    [install.sh] -- New python executable in ./env/bin/python
    Installing setuptools, pip...
    [install.sh] -- done.
    [install.sh] -- Collecting git+git://git.symlink.me/pub/romain/weboob (from -r requirements.txt (line 1))


And in the web console :
```
"WARNING: Missing translation for key: "update failed"" vendor.js:30471
"normal error before refactoring..." 7 6 jquery.dataTables.addTr.js:13
TypeError: oa is not a function highcharts.js:35
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the    object with the correct initial [[Prototype]] value using Object.create main.js:428
"Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>." react.js:19527 ```

**Comment by bnjbvr** [comment]
So the installation is working quite normally, I suppose. After a few minutes (up to 10 minutes), do you still have the installation page, or do you reach the main actual page?

**Comment by 0liUms** [comment]
Update of cozy, news in the logs windows :
```
Is it installed?
=> No it isn't. Installing weboob...
[install.sh] -- New python executable in ./env/bin/python
Installing setuptools, pip...
[install.sh] -- done.
[install.sh] -- You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[install.sh] -- Collecting git+git://git.symlink.me/pub/romain/weboob (from -r requirements.txt (line 1))
[install.sh] --   Cloning git://git.symlink.me/pub/romain/weboob to /tmp/pip-zXUxEq-build
[install.sh] stderr -- fatal: unable to connect to git.symlink.me:
git.symlink.me[0: 88.198.11.130]: errno=Connection timed out
git.symlink.me[1: 2a01:4f8:130:3062::1]: errno=Connection timed out
[install.sh] --   Complete output from command /usr/bin/git clone -q git://git.symlink.me/pub/romain/weboob /tmp/pip-zXUxEq-build:
  
  ----------------------------------------
  Command "/usr/bin/git clone -q git://git.symlink.me/pub/romain/weboob /tmp/pip-zXUxEq-build" failed with error code 128 in None
[install.sh] closed with code: 1
```
Em, I got stressed firewall rules. Any relation ?

**Comment by bnjbvr** [comment]
Probably: to install the dependencies, the kresus user (cozy-kresus) needs to be able to clone the git repository located at git.symlink.me, also clone a module from the pypi repository,. Obviously, kresus also needs to be able to connect (http/https) to your bank website. Could adding this to the README have helped you?

**Comment by bnjbvr** [comment]
Any news, @0liUms ?

**Comment by 0liUms** [comment]
No I'm sorry but I don't use Cozy anymore :/
But yes, I think it was my firewall. Yeah I think it can be great to have this in the README :)

**Comment by bnjbvr** [comment]
OK, I'll morph this bug then.
Teaser: Kresus should be available without a Cozy instance, soonish...

**Comment by 0liUms** [comment]
Interesting ! :)

**Comment by EtienneM** [comment]
Will it still be available with Cozy? Or do you plan to completely give up the Cozy support?...  :'(

**Comment by bnjbvr** [comment]
@EtienneM , no worries, the code should be generic enough so both versions can co-exist. The Cozy version likely will likely have more features (notifications, email reports,...), but having a standalone version should help getting more traction.
