### ISSUE TITLE
Wrong shown Balance

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#61]
Hello,

the displayed balance on the "RApports" page is wrong. It seams you display 
InitialAmount+Sum of all operations.
Without taking into account the date of InitialAmount.
InitialAmount is the value of the account when imported in kresus (from what I see), and some of the operations (all at first imports) are previous to InitialAmount.
The graphs are not correctly displayed.

The bank is LCL (and the weboob module maybe bugged) 

Thanks

**Comment by bnjbvr** [comment]
Thanks for reporting! Coincidentally, I've noticed the issue as well and fixed it in the "incoming" branch. A new release shall be made today, so please wait for the notification, update kresus and then delete/re-add your account (or change the value by yourself, by using the data browser app).

**Comment by bnjbvr** [comment]
Fixed by ebe5a9be7db8955467924f798e7702c2e0fc708a.
