### ISSUE TITLE
Last transaction not imported

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#62]
I am not sure this due to kresus and not to weboob. The last transction of my account is not imported, even after update of the account. The transaction is not in the couchdb either, and as been recorded 3 days ago.

**Comment by ZeHiro** [comment]
Weboob related, the operation is not downloaded either by bankoob

**Comment by bnjbvr** [comment]
Wow, so great you could test it, thank you! If it is still not loaded in a few days, it might be worth opening a bug on the weboob side...

**Comment by ZeHiro** [comment]
It's on its way. I should have tested bankoob first.

**Comment by bnjbvr** [comment]
What's the status here? Did the operation get imported? Can we close?

**Comment by ZeHiro** [comment]
Yes it can be closed
