### ISSUE TITLE
Weird warning in logs

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#63]
Hi,

here is a weired warning log : 

/usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

I know it is a weboob problem but is it due to a wrong install?

**Comment by bnjbvr** [comment]
I've seen it before for one of my bank but not the other one, so I guess that's dependent to Weboob. We should test with boobank, to find out whether it's specific to kresus or weboob.

**Comment by ZeHiro** [comment]
Tested it on my account, it is weboob related.

**Comment by bnjbvr** [comment]
Thanks. I could ignore the insecure platform warning as suggested in the link, but I would rather not do this. Closing, as there's not much to do on the Kresus side. Thanks for the report!
