### ISSUE TITLE
Wrong "Dernière synchronisation avec votre banque :" date

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#64]
The date used on the "Rapports" page when resynching transaction is not lastChecked value of couchDB. Is it the expected behaviour?

**Comment by bnjbvr** [comment]
Good catch! Thank you for all the bug reports, you're really helping me :+1:

**Comment by ZeHiro** [comment]
Still not good when clicking "Synchronize now"

**Comment by bnjbvr** [comment]
Just checked right now and it works locally. Can you force reloading (Ctrl Shift R or Ctrl F5) and retry, please?

**Comment by ZeHiro** [comment]
On 0.5, the date is only updated after a reload of the page.

**Comment by bnjbvr** [comment]
Duh, I never learn. Thanks.
