### ISSUE TITLE
Error when navigating betwwen banks

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#65]
Hello,
I have several banks configured in my cozy.  One bak has several accounts
When I navigate between banks, at some points I get this error  (I sanitized the domain):  

Assertion error: object should have property c3bb32ce49195bba8f0d916f86025ea7
assert@https://cozy.mydomain.tld/apps/kresus/js/main.js:80:68
has@https://cozy.mydomain.tld/apps/kresus/js/main.js:95:12
[23]</store.getCurrentAccount@https://cozy.mydomain.tld/apps/kresus/js/main.js:4520:5
_accountListener@https://cozy.mydomain.tld/apps/kresus/js/main.js:2172:30
[24]</EventEmitter.prototype.emit@https://cozy.mydomain.tld/apps/kresus/js/main.js:5110:7
[23]</<@https://cozy.mydomain.tld/apps/kresus/js/main.js:4893:13
[18]</Dispatcher.prototype.$Dispatcher_invokeCallback@https://cozy.mydomain.tld/apps/kresus/js/main.js:3864:3
[18]</Dispatcher.prototype.dispatch@https://cozy.mydomain.tld/apps/kresus/js/main.js:3839:7
[23]</store.loadAccountsCurrentBank/<@https://cozy.mydomain.tld/apps/kresus/js/main.js:4651:1
getAccounts/<@https://cozy.mydomain.tld/apps/kresus/js/main.js:279:13
_.Callbacks/k@https://cozy.mydomain.tld/apps/kresus/js/vendor/jquery.js:24:22270
_.Callbacks/l.fireWith@https://cozy.mydomain.tld/apps/kresus/js/vendor/jquery.js:24:23087
c@https://cozy.mydomain.tld/apps/kresus/js/vendor/jquery.js:25:27607
.send/b/<@https://cozy.mydomain.tld/apps/kresus/js/vendor/jquery.js:26:1379

In fact, when changing of bank, the interface does not select an account of the new bank, which it should do. 

Kresus version : 0.4.4

**Comment by ZeHiro** [comment]
Hello @ bnjbvr,
this ticket does not seem to be fixed. 

The error in the console of firefox no points to : 

 main.js:2279

Which is : 

Corresponds to code  : 

                        " " + new Date(this.state.account.lastChecked).toLocaleString()
Here : 

https://github.com/bnjbvr/kresus/blob/71a40dc96e56f147ddb7353ad581fad5ad33a738/client/components/OperationList.js#L235

**Comment by bnjbvr** [comment]
Oh boy, probably a different issue. What do you see, exactly? Is it something like "this.state.account is undefined"?

**Comment by ZeHiro** [comment]
I have the same popup as before. 
The error in the JS console of firefox is : 

TypeError: this.state.account is undefined

**Comment by bnjbvr** [comment]
I understand why the error could show up in theory, but in practice I can't reproduce it. What's the typical response time when you're clicking on a bank link? (bottom-left section of the menu bar)
Do you do particular things to trigger this issue?

**Comment by ZeHiro** [comment]
A few seconds (2-3)

**Comment by ZeHiro** [comment]
It only appears when the "Rapports" view

**Comment by ZeHiro** [comment]
Not systematic anymore. The error does not pop anymore.

**Comment by bnjbvr** [comment]
OK, I suspect some browser cache issue (after a Kresus update, force reloading might preview this kind of problems, with Ctrl Shift R on Firefox). Please let me know if this reproduces in the next days, otherwise I'll close the issue.

**Comment by ZeHiro** [comment]
I guess it was also a cache issue (and maybe also  ith proxy of my company blocking some stuff)

**Comment by bnjbvr** [comment]
Cool, I'll close then, feel free to reopen in any case it shows up again :)

**Comment by ZeHiro** [comment]
It showed up again. In fact it happend when changing of bank when operation list is being downloaded, and no cache for the operation list is present.
