### ISSUE TITLE
Change update process

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#67]
I don know I there is a plain "update process", or updating just means installing the new version (the script run to update kresus is exactly the same when updating and installing), but I ca see several improvements : 
- Update the new version of kersus only when the rest of the update is OK. Here is what happened to me :  The update of kresus failed (don know why), and when and kresus was seen as "cassée" by cozy. I relaunched kresus in cozy (not the update), the version of kresus was set to 0.4.4, even if update failed. I fear the update notification won't be seen then

- Check if webbob is installed before reinstalling it

**Comment by bnjbvr** [comment]
So I am not sure to quite understand (feel free to continue in French if that can be simpler): you're saying that you updated kresus, then cozy saw kresus as broken ("cassée") and the version of kresus was still set to the updated version, even though Kresus installation was broken? If this interpretation is correct, that's an issue in cozy-home, not in kresus itself :)

For the second part, there is already such a check: at startup, kresus tests if weboob is installed, and if it is, it tests that it works correctly by running a dummy script. If you've experienced several re-installations of weboob in a row, that's a bug, but I would need more details...

**Comment by ZeHiro** [comment]
For first point : 
- you understood well. I report to cozy-home

- Second point : when updating kresus, kresus was fully reinstalled, including reinstall of weboob,  instead of checking first if weboob is installed.

**Comment by bnjbvr** [comment]
OK. For the second part:
- installing or updating kresus will just install the server / client files. Weboob isn't installed at this point.
- we check weboob's status when starting the app:
  - if weboob isn't installed, we install it. That uses the KresusConfig `weboob-installed` value, and if it is set to `false`, installation starts.
  - if weboob is installed, we test the installation worked by running a small script ( https://github.com/bnjbvr/kresus/blob/master/weboob/scripts/test.sh ). If the status code of this test isn't 0, then it means weboob installation didn't work somehow: in this case, we set `weboob-installed` to `false` and relaunch the installation.

So updating Kresus via the cozy interface shouldn't update weboob *all the time*, if weboob installation previously worked. I've just tried, and it works as expected on my 3 instances. Can you trigger an update of kresus after weboob is installed, and let me know if you weboob gets re-installed? (which you can detect by seeing the installation video / log when reloading kresus, right after restarting it)

**Comment by bnjbvr** [comment]
@ZeHiro, can you give me feedback regarding my previous comment, please? otherwise I am afraid this issue won't be actionable...

**Comment by bnjbvr** [comment]
As of today, on the incoming branch, Weboob is locally installed, if and only if, it wasn't globally installed beforehand. Moreover, there are different action processes for only updating weboob (not reinstalling it from scratch), so I guess a lot has been done already and the install/update process is getting better. Feel free to reopen if you do not think the same, with some input :)
