### ISSUE TITLE
Save settings on the server side

### ISSUE THREAD

**Issue by pierrerousseau** [bnjbvr/kresus#72]
When I synchronize my bank account, the settings are back to default (duplicate treshold) and the erased account are back.

**Comment by bnjbvr** [comment]
Good catch! There's a TODO about that in the code, because the duplicate threshold was implemented before configuration pairs were implemented. Out of curiosity, would you be interested in implementing this? I would happily guide you through the steps :)

**Comment by bnjbvr** [comment]
Owait, did i just misread very badly? Sorry about that. So you're observing that synchronizing accounts will show deleted accounts back? That's pretty terrible...

**Comment by bnjbvr** [comment]
Ha, thinking about it slightly more, it's because synchronizing will automatically reload accounts, so deleting accounts might be effectless... See also issue #47. Morphing this one as described in my first comment.

**Comment by pierrerousseau** [comment]
I don't think that I will have time to do it before a few weeks/months, so do not count on me. If nothing moved till that time, I'll check.
