### ISSUE TITLE
Route error?

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#78]
Hi,
when trying to understand the code, I found this :  

In https://github.com/bnjbvr/kresus/blob/master/server/controllers/routes.coffee

l 80 : get: weboob.update

shouldn't this be 

put: weboob:update

?

**Comment by bnjbvr** [comment]
Nope, as the frontend uses a GET request to reach that endpoint ( https://github.com/bnjbvr/kresus/blob/master/client/backends/http.js#L180 ). URLs could be enhanced to follow REST semantics better, but it's more a nice-to-have than an important prerequisite :)
