### ISSUE TITLE
Fetching your latest bank transactions..

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#81]
"Fetching your latest bank transactions.." 

Is not translated to french (there does not seem to be a translation either in the "local/fr.js" file)

**Comment by bnjbvr** [comment]
Thanks for the report! For the record, this line needs to be changed ( https://github.com/bnjbvr/kresus/blob/master/client/components/OperationList.js#L231 ) and a key needs to be added in the FR locale.
