### ISSUE TITLE
Fill "app" field in couchdb

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#83]
Hello,

the field "app" does not seem to be filled when sending a notification (as displayed in databrowser)

Also, the same notification was raised 4 times for the same import (or duplicate detection), shouldn't there be only one? (I didn chechk my cozy for a few days).

**Comment by bnjbvr** [comment]
Hi. I don't know much the code of the notification helper, so maybe the fact that the "field" app isn't filled is an issue from it? (however, I can't imagine how it could be not filled, as clicking on the notification opens kresus as expected).
I just checked the code, and it seems the notification is sent each time we import new operations. Can it be that new operations have been imported in different accounts / different bank accounts?

**Comment by bnjbvr** [comment]
Just checked on my test instance, it works as a charm and the "app" field is correctly filled. Closing for now, let me know if this happens again for you.
