### ISSUE TITLE
Make bank operation linking proper

### ISSUE THREAD

**Issue by frankrousseau** [bnjbvr/kresus#91]
A user reported in the forum that the bank operation linking should be displayed more clearly. Moreover he mentioned that the headers was not properly set `text/html` instead of `application/pdf`.

**Comment by bnjbvr** [comment]
Thanks for the report. Weird that Firefox Nightly correctly opens pdfjs for reading the file, I guess this is browser specific defined.
I was wondering, do you think it'd be better that the link be on the transaction label (rather than the amount)?

**Comment by ZeHiro** [comment]
Hi,
I reported the bug on the forum. 
Maybe an Icon (like the "label icon" of Files application) added in the "Operation" column before the operation name and linking to the files would highlight well the link to the facture.
