### ISSUE TITLE
Retrieve attached file's name

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#97]
Hi,
When a facture is linked to a facture inside "Files" app, if I click on the icon, the name of the downloaded file is always file (eventually file(1), file(2)...) not the name of the pdf file inside "Files" app.

Thanks

**Comment by bnjbvr** [comment]
Thanks! This one is harder than the others. Kresus does not have access to the files, and I'd prefer that it stays as is. However, the file's name is part of the metadata information associated to the file, so as long as K stays away from file, it won't be able to retrieve the pdf's name from the Files app, nor can it find the actual content type (I've set it to `application/pdf`, guessing all bills would be PDFs, but that could change in the future). Or we could have Kresus allow to change the file attached to an operation, but that's much more work (display files, etc.).

@frankrousseau, is there any easy way to retrieve the file's name?

**Comment by ZeHiro** [comment]
Konnectors now provides a file name.

**Comment by bnjbvr** [comment]
https://github.com/bnjbvr/kresus/commit/deb3eab132f544b3f9e29ced34174f263099dbc8
