### ISSUE TITLE
Update accounts at start of app if date(now) > date(next update)

### ISSUE THREAD

**Issue by ZeHiro** [bnjbvr/kresus#99]
When "auto stop" box is checked, kresus is automatically stopped. If kresus is stopped during one night, the automatic update is not done. Manual update is necessary.

**Comment by bnjbvr** [comment]
Indeed! With the latest versions of cozy, the "auto stop" checkbox isn't checked automatically by default anymore, so that's fine (as long as you have enough RAM :D). What we could do instead is just trying to load operations at start, if there's at least one live account, that seems simpler.

**Comment by ZeHiro** [comment]
By update, I meant fetching new operations with weboob. This can be done quite easily, if I understand well the start up procedure. Like : 

if date (now) > date (next update) 
then 
checkAllAccesses
else 
prepareNextCheck

**Comment by bnjbvr** [comment]
Well, the issue is that if Kresus got stopped, the value of `nextUpdate` got lost, so we just can't do the comparison :) Polling accounts at start, if there are any, definitely sounds OK to me.

**Comment by ZeHiro** [comment]
There is a "lastChecked" field for each account. This could be used to update the accounts.
